### ISSUE TITLE
Run Storybook - "path" argument must be of type string

### ISSUE THREAD

**Issue by lucasishuman** [open-wc/open-wc#1025]
Get the following error when trying to `npm run storybook`

I created my project up using the `Application` scaffold generator with all features enabled.

- MacOS 10.14.6
- Node versions tested: 11.9 / 12.2 / 13.2
- NPM version: 6.9.0

I am able to successfully `npm run storybook:build` 

```sh
→ npm run storybook

> dd-ui-dev@0.0.0 storybook /Users/lshuman/Sites/dd-ui-dev
> start-storybook --stories 'components/*/stories/*.stories.{js,mdx}' --node-resolve --watch --open

(node:79303) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:113:11)
    at Object.resolve (path.js:980:7)
    at run (/Users/lshuman/Sites/dd-ui-dev/node_modules/@open-wc/demoing-storybook/src/start/cli.js:18:24)
    at Object.<anonymous> (/Users/lshuman/Sites/dd-ui-dev/node_modules/@open-wc/demoing-storybook/src/start/cli.js:70:1)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:67:12)
    at internal/main/run_main_module.js:17:47
(node:79303) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:79303) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
This is an *amazing* project. So happy to have found it and very excited to use it. Thank you for all your efforts! 😀

**Comment by StarZeus** [comment]
We need to supply --root-dir command line arg.

updating "storybook" npm script as follows resolves the problem

`"storybook":"start-storybook --node-resolve --watch --open --root-dir ."`

**Comment by lucasishuman** [comment]
That worked - thank you!

**Comment by LarsDenBakker** [comment]
Reopening this, its really a bug. The current working directory should be the default :)

Thanks for reporting it.
