### ISSUE TITLE
[karma-esm] fails to test

### ISSUE THREAD

**Issue by bennypowers** [open-wc/open-wc#1134]
# Description
Running tests produces a `TypeError` : 'map of undefined'. This occurs when `setup-es-dev-server.js:30` searches for instances of script tags on the karma page

# Steps to Reproduce
```
git clone git@github.com:bennypowers/stripe-elements.git
cd stripe-elements
git checkout create-source
npm ci
npm t
```

# Expected
Tests!

# Actual
```
~/D/stripe-elements $ npm t 
> @power-elements/stripe-elements@1.1.2 test /Users/bennyp/Documents/stripe-elements
> karma start --coverage


START:
15 12 2019 18:40:55.406:WARN [filelist]: Pattern "/Users/bennyp/Documents/stripe-elements/__snapshots__/**/*.md" does not match any file.
15 12 2019 18:40:55.418:INFO [karma-server]: Karma v4.4.1 server started at http://0.0.0.0:9876/
15 12 2019 18:40:55.418:INFO [launcher]: Launching browsers ChromeHeadlessNoSandbox with concurrency unlimited
15 12 2019 18:40:55.421:INFO [launcher]: Starting browser ChromeHeadless
15 12 2019 18:40:55.950:INFO [HeadlessChrome 79.0.3945 (Mac OS X 10.14.6)]: Connected on socket IpLKwVR6PB7COQ4AAAAA with id 6825825

  TypeError: Cannot read property 'map' of null
      at fetchKarmaHTML (/Users/bennyp/Documents/stripe-elements/node_modules/@open-wc/karma-esm/src/setup-es-dev-server.js:62:6)
      at processTicksAndRejections (internal/process/task_queues.js:89:5)
      at async responseTransformMiddlewareConfig (/Users/bennyp/Documents/stripe-elements/node_modules/es-dev-server/dist/middleware/response-transform.js:65:22)
      at async transformIndexHTMLMiddleware (/Users/bennyp/Documents/stripe-elements/node_modules/es-dev-server/dist/middleware/transform-index-html.js:102:5)
      at async watchServedFilesMiddleware (/Users/bennyp/Documents/stripe-elements/node_modules/es-dev-server/dist/middleware/watch-served-files.js:40:5)
      at async responseBodyCacheMiddleware (/Users/bennyp/Documents/stripe-elements/node_modules/es-dev-server/dist/middleware/response-body-cache.js:118:5)
      at async etagCacheMiddleware (/Users/bennyp/Documents/stripe-elements/node_modules/es-dev-server/dist/middleware/etag-cache.js:14:5)
      at async /Users/bennyp/Documents/stripe-elements/node_modules/es-dev-server/dist/create-middlewares.js:117:5
      at async log404 (/Users/bennyp/Documents/stripe-elements/node_modules/@open-wc/karma-esm/src/esm-config.js:38:7)
      at async /Users/bennyp/Documents/stripe-elements/node_modules/koa-compress/index.js:38:5
```
Correcting that line (String#match returns null, instead of an empty array, if no matches are found) results in:

```
 ~/D/stripe-elements $ npm t 
> @power-elements/stripe-elements@1.1.2 test /Users/bennyp/Documents/stripe-elements
> karma start --coverage


START:
15 12 2019 18:47:40.073:WARN [filelist]: Pattern "/Users/bennyp/Documents/stripe-elements/__snapshots__/**/*.md" does not match any file.
15 12 2019 18:47:40.085:INFO [karma-server]: Karma v4.4.1 server started at http://0.0.0.0:9876/
15 12 2019 18:47:40.086:INFO [launcher]: Launching browsers ChromeHeadlessNoSandbox with concurrency unlimited
15 12 2019 18:47:40.090:INFO [launcher]: Starting browser ChromeHeadless
15 12 2019 18:47:40.629:INFO [HeadlessChrome 79.0.3945 (Mac OS X 10.14.6)]: Connected on socket 7-JlLNLf2b8TnZXSAAAA with id 6158904
Dynamic import can only be supported when transforming ES modules to AMD, CommonJS or SystemJS. Only the parser plugin will be enabled.
HeadlessChrome 79.0.3945 (Mac OS X 10.14.6) ERROR
  Uncaught SyntaxError: Cannot use import statement outside a module
  at src/stripe-elements.test.js:1:1

  SyntaxError: Cannot use import statement outside a module
HeadlessChrome 79.0.3945 (Mac OS X 10.14.6) ERROR
  Uncaught SyntaxError: Cannot use import statement outside a module
  at src/stripe-elements.test.js:1:1

  SyntaxError: Cannot use import statement outside a module

Finished in 0.434 secs / 0 secs @ 18:47:41 GMT+0200 (Israel Standard Time)

SUMMARY:
✔ 0 tests completed

=============================== Coverage summary ===============================
Statements   : Unknown% ( 0/0 )
Branches     : Unknown% ( 0/0 )
Functions    : Unknown% ( 0/0 )
Lines        : Unknown% ( 0/0 )
================================================================================
npm ERR! Test failed.  See above for more details.
```

The karma page for this test shows the error `SyntaxError: import declarations may only appear at top level of a module` in console.

**Comment by LarsDenBakker** [comment]
The problem is that you're missing `type="module"` in your test pattern. We definitely need to add better error logging for this.
