### ISSUE TITLE
[es-dev-server] unhandled exception when `fileWatcher` is not defined.

### ISSUE THREAD

**Issue by goremikin** [open-wc/open-wc#1157]
Hello, when I create es-dev-server programmatically via `createServer({ watch: false })`, I do not want to enable watch mode, so I do not provide `fileWatcher` . However when resolving files I get an unhandled error:

`UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'add' of undefined
    at watchServedFile (/node_modules/es-dev-server/dist/middleware/watch-served-files.js:27:19)
    at watchServedFilesMiddleware (/node_modules/es-dev-server/dist/middleware/watch-served-files.js:41:5)
`

The problem is caused by the fact that `watch-served-files.js` middleware is applied regardless `watch` flag or presence of `fileWatcher`.

**Comment by LarsDenBakker** [comment]
The file watcher is necessary also without watch mode, because it's used for busting the transform cache.

**Comment by goremikin** [comment]
In that case I would expect the file watcher to be created internally by es-dev-server itself

**Comment by LarsDenBakker** [comment]
`startServer` does create one by itself if one isn't given, but `createServer` isn't. Will accept a PR that adds this is in :)
