### ISSUE TITLE
[es-dev-server] Active babel on chrome fails on dynamic import

### ISSUE THREAD

**Issue by jorenbroekema** [open-wc/open-wc#1168]
I am using demoing-storybook which uses es-dev-server to run prebuilt Storybook.

When using dynamic imports in my code, the es-dev-server terminal gives me the following error:
```
SyntaxError: unknown: Support for the experimental syntax 'dynamicImport' isn't currently enabled (120:14):
  
    118 |   {html`
    119 |     <lion-icon
  > 120 |       .svg=${import('./icons/bugs/bug05.svg.js')}
        |              ^
    121 |       aria-label="Skinny dung beatle"
    122 |     ></lion-icon>
    123 |   `}
  
  Add @babel/plugin-syntax-dynamic-import (https://git.io/vb4Sv) to the 'plugins' section of your Babel config to enable parsing.
      at Object.raise (/home/joren/code/lion/node_modules/@babel/parser/lib/index.js:6983:17)
      at Object.expectPlugin (/home/joren/code/lion/node_modules/@babel/parser/lib/index.js:8381:18)
      at Object.parseExprAtom (/home/joren/code/lion/node_modules/@babel/parser/lib/index.js:9473:14)
      at Object.parseExprAtom (/home/joren/code/lion/node_modules/@babel/parser/lib/index.js:4097:20)
      at Object.parseExprSubscripts (/home/joren/code/lion/node_modules/@babel/parser/lib/index.js:9213:23)
      at Object.parseMaybeUnary (/home/joren/code/lion/node_modules/@babel/parser/lib/index.js:9193:21)
      at Object.parseExprOps (/home/joren/code/lion/node_modules/@babel/parser/lib/index.js:9059:23)
      at Object.parseMaybeConditional (/home/joren/code/lion/node_modules/@babel/parser/lib/index.js:9032:23)
      at Object.parseMaybeAssign (/home/joren/code/lion/node_modules/@babel/parser/lib/index.js:8978:21)
      at Object.parseExpression (/home/joren/code/lion/node_modules/@babel/parser/lib/index.js:8928:23)
```

In the browser I get `Uncaught (in promise) TypeError: Failed to fetch dynamically imported module`

Code to reproduce: 
```js
<Story name="Dynamic">
  {html`
    <lion-icon .svg=${import('./icons/bugs/bug05.svg.js')}></lion-icon>
  `}
</Story>
```

This is on Google Chrome Version 79.0.3945.88 (Official Build) (64-bit), so it's interesting why babel is running on that.

**Comment by LarsDenBakker** [comment]
Babel is used by the mdx transform tool that we (have to) use to convert the stories. I spent some time trying to fix it, but it's a big wormhole of tools. Need to dig a little further still. Did this work with the regular storybook + mdx?

**Comment by LarsDenBakker** [comment]
The babel setup is all hardcoded inside the mdx transform here: https://github.com/mdx-js/mdx/blob/master/packages/mdx/mdx-hast-to-jsx.js#L119 there isn't anything we can do.

MDX is a pretty funky format in general, it trips up pretty quickly because of whitespace or newlines.

**Comment by jorenbroekema** [comment]
Hey, I never tried it in regular storybook + mdx. Migrated straight to new storybook + new format.

Do you think it would make sense for us to fire an issue and ask if there is something they can do, or something we can do to work around it?

So far the dynamic import I only need once but there are some follow-up stories that rely more on dynamic import, so any idea what route I could try to figure out some kind of solution?

**Comment by LarsDenBakker** [comment]
Yes we should open an issue at the mdx tool. In the meantime you could just write regular stories for this.

**Comment by jorenbroekema** [comment]
I've created an issue in their repo ^

**Comment by LarsDenBakker** [comment]
I'm going to close this issue, as it's not related to open-wc. Very annoying though :(
