### ISSUE TITLE
[karma-esm] version higher than 2.9.8 has problems with karma-viewport framework

### ISSUE THREAD

**Issue by sebastiangora** [open-wc/open-wc#1289]
Starting from karma-esm `2.10.1` when I'm including karma-viewport like this:

```js
frameworks: ['viewport'],
esm: {
    nodeResolve: true,
    exclude: ['**/node_modules/karma-viewport/**/*.json.js'],
},
```

I have errors:
```console
START:
31 01 2020 09:37:51.879:INFO [karma-server]: Karma v4.4.1 server started at http://0.0.0.0:9876/
31 01 2020 09:37:51.882:INFO [launcher]: Launching browsers ChromeHeadlessNoSandbox with concurrency unlimited
31 01 2020 09:37:51.892:INFO [launcher]: Starting browser ChromeHeadless
31 01 2020 09:37:52.573:INFO [HeadlessChrome 79.0.3945 (Windows 10.0.0)]: Connected on socket qTee_q5we908UT_zAAAA with id 18822107
[karma-esm]: Could not find requested file: /node_modules/karma-viewport/dist/config/default.json.js?d74df6fc8ebb31118b0c9710eab2dba5f09da45c
[karma-esm]: Could not find requested file: /node_modules/karma-viewport/dist/config/default.json.js?d74df6fc8ebb31118b0c9710eab2dba5f09da45c
HeadlessChrome 79.0.3945 (Windows 10.0.0) ERROR
  Uncaught TypeError: Cannot read property 'context' of undefined
  at node_modules/karma-viewport/dist/adapter/index.js:1:2575

  TypeError: Cannot read property 'context' of undefined
      at new e (node_modules/karma-viewport/dist/adapter/webpack:/src/adapter/viewport.ts:134:56)
      at node_modules/karma-viewport/dist/adapter/webpack:/src/adapter/index.ts:47:21
      at Object.call (node_modules/karma-viewport/dist/adapter/webpack:/src/adapter/index.ts:46:1)
      at n (node_modules/karma-viewport/dist/adapter/webpack:/webpack/bootstrap:19:22)
      at Object.call (node_modules/karma-viewport/dist/adapter/index.js:1:993)
      at __webpack_require__ (node_modules/karma-viewport/dist/adapter/webpack:/webpack/bootstrap:19:22)
      at node_modules/karma-viewport/dist/adapter/webpack:/webpack/bootstrap:83:10
      at node_modules/karma-viewport/dist/adapter/index.js:1:965
```
I'm using `reateDefaultConfig` from `@open-wc/testing-karma`, version `2.9.8` is working with this configuration. 
I believe this is connected with this lines
```js
esmConfig.babelExclude = [
    ...(esmConfig.babelExclude || []),
    // exclude regular test scripts/libs from babel
    ...karmaConfig.files
      .filter(f => f.pattern.endsWith('.js') && f.type !== 'module')
      .map(f => f.pattern),
  ];
```
from [commit](https://github.com/open-wc/open-wc/commit/7d5ea56a1cb911fb31228bec18dc38ea8826b1f4).

**Comment by carlosmmdiaz** [comment]
Hi there,

We have exactly the same problem in our team:

```bash
13 05 2020 15:24:50.636:INFO [karma-server]: Karma v4.4.1 server started at http://0.0.0.0:9876/
13 05 2020 15:24:50.637:INFO [launcher]: Launching browsers ChromeHeadlessNoSandbox with concurrency unlimited
13 05 2020 15:24:50.642:INFO [launcher]: Starting browser ChromeHeadless
13 05 2020 15:24:51.255:INFO [HeadlessChrome 81.0.4044 (Mac OS X 10.14.6)]: Connected on socket wWFIFhHa0C3MclV8AAAA with id 94238269
[karma-esm]: Could not find requested file: /node_modules/karma-viewport/dist/config/default.json.js?f98e38d0e10ae3a2ebc58886afa55ba0a891f91a
[karma-esm]: Could not find requested file: /node_modules/karma-viewport/dist/config/default.json.js?f98e38d0e10ae3a2ebc58886afa55ba0a891f91a
HeadlessChrome 81.0.4044 (Mac OS X 10.14.6) ERROR
  Uncaught TypeError: Cannot read property 'context' of undefined
  at node_modules/karma-viewport/dist/adapter/index.js:1:1592
  
  TypeError: Cannot read property 'context' of undefined
      at new e (node_modules/karma-viewport/dist/adapter/webpack:/src/adapter/viewport.ts:134:56)
      at node_modules/karma-viewport/dist/adapter/webpack:/src/adapter/index.ts:47:21
      at Object.call (node_modules/karma-viewport/dist/adapter/webpack:/src/adapter/index.ts:46:1)
      at n (node_modules/karma-viewport/dist/adapter/webpack:/webpack/bootstrap:19:22)
      at Object.call (node_modules/karma-viewport/dist/adapter/index.js:1:993)
      at __webpack_require__ (node_modules/karma-viewport/dist/adapter/webpack:/webpack/bootstrap:19:22)
      at node_modules/karma-viewport/dist/adapter/webpack:/webpack/bootstrap:83:10
      at node_modules/karma-viewport/dist/adapter/index.js:1:965
HeadlessChrome 81.0.4044 (Mac OS X 10.14.6) ERROR
  Uncaught TypeError: Cannot read property 'context' of undefined
  at node_modules/karma-viewport/dist/adapter/index.js:1:1592
  
  TypeError: Cannot read property 'context' of undefined
      at new e (node_modules/karma-viewport/dist/adapter/webpack:/src/adapter/viewport.ts:134:56)
      at node_modules/karma-viewport/dist/adapter/webpack:/src/adapter/index.ts:47:21
      at Object.call (node_modules/karma-viewport/dist/adapter/webpack:/src/adapter/index.ts:46:1)
      at n (node_modules/karma-viewport/dist/adapter/webpack:/webpack/bootstrap:19:22)
      at Object.call (node_modules/karma-viewport/dist/adapter/index.js:1:993)
      at __webpack_require__ (node_modules/karma-viewport/dist/adapter/webpack:/webpack/bootstrap:19:22)
      at node_modules/karma-viewport/dist/adapter/webpack:/webpack/bootstrap:83:10
      at node_modules/karma-viewport/dist/adapter/index.js:1:965
```

This is our karma.config file:

```js
/* eslint-disable import/no-extraneous-dependencies */
const { createDefaultConfig } = require('@open-wc/testing-karma');
const deepmerge = require('deepmerge');
const { breakpoints } = require('./viewports.config.js');

module.exports = config => {
  config.set(
    deepmerge(createDefaultConfig(config), {
      files: [
        // runs all files ending with .test in the test folder,
        // can be overwritten by passing a --grep flag. examples:
        //
        // npm run test -- --grep test/foo/bar.test.js
        // npm run test -- --grep test/bar/*
        {
          pattern: config.grep ? config.grep : 'packages/*/*/test/**/*.test.js',
          type: 'module',
        },
      ],

      // see the karma-esm docs for all options
      esm: {
        // if you are using 'bare module imports' you will need this option
        nodeResolve: true,

        // Custom babel config to replace the process node enviroment
        // Right now this get used by Redux
        // Note: We could change this for redux.mjs 
        babelConfig: {
          plugins: [
            [
              'transform-define',
              {
                'process.env.NODE_ENV': 'production',
              },
            ],
          ],
        },
      },

      frameworks: ['viewport'],

      // This allow us to test our component with different viewports
      viewport: {
        context: '#viewport',
        breakpoints,
      },

      // Test coverage settings:
      coverageIstanbulReporter: {
        thresholds: {
          emitWarning: false,
          global: {
            statements: 80,
            branches: 80,
            functions: 80,
            lines: 80,
          },
        },
      },
    }),
  );

  return config;
};
```

Any idea is this could be fixed or another way to have unit-test and test different viewports using karma-esm?

Thank you 🙏

**Comment by dpinillos37** [comment]
I have the same issue, any idea on when this will be fixed?

**Comment by imtiyazthange** [comment]
Same issue here, did you guys got a fix for this one.
```

01 09 2020 16:28:18.029:INFO [karma-server]: Karma v5.1.1 server started at http://localhost:9876/
01 09 2020 16:28:18.031:INFO [launcher]: Launching browsers ChromeHeadlessNoSandbox with concurrency unlimited
01 09 2020 16:28:18.037:INFO [launcher]: Starting browser ChromeHeadless
01 09 2020 16:28:20.601:INFO [Chrome Headless 85.0.4183.83 (Windows 10)]: Connected on socket 4nRHOcOUlyVl9aHlAAAA with id 38001012
01 09 2020 16:28:20.805:WARN [middleware:karma]: Unable to determine file type from the file extension, defaulting to js.
  To silence the warning specify a valid type for D:/Work/Source/SupportTools/PLPWebComponents/node_modules/karma-viewport/dist/adapter/index.js.map in the configuration file.
  See http://karma-runner.github.io/latest/config/files.html
[karma-esm]: Could not find requested file: /node_modules/karma-viewport/dist/config/default.json.js?d74df6fc8ebb31118b0c9710eab2dba5f09da45c
[karma-esm]: Could not find requested file: /node_modules/karma-viewport/dist/config/default.json.js?d74df6fc8ebb31118b0c9710eab2dba5f09da45c
Chrome Headless 85.0.4183.83 (Windows 10) ERROR
  Uncaught TypeError: Cannot read property 'context' of undefined
  at node_modules/karma-viewport/dist/adapter/index.js:1:1618
  
  TypeError: Cannot read property 'context' of undefined
      at new e (node_modules/karma-viewport/dist/adapter/webpack:/src/adapter/viewport.ts:134:56)
      at node_modules/karma-viewport/dist/adapter/webpack:/src/adapter/index.ts:47:21
      at Object.call (node_modules/karma-viewport/dist/adapter/webpack:/src/adapter/index.ts:46:1)
      at n (node_modules/karma-viewport/dist/adapter/webpack:/webpack/bootstrap:19:22)
      at Object.call (node_modules/karma-viewport/dist/adapter/index.js:1:993)
      at __webpack_require__ (node_modules/karma-viewport/dist/adapter/webpack:/webpack/bootstrap:19:22)
      at node_modules/karma-viewport/dist/adapter/webpack:/webpack/bootstrap:83:10
      at node_modules/karma-viewport/dist/adapter/index.js:1:965

Finished in 0.529 secs / 0 secs @ 16:28:21 GMT-0400 (Eastern Daylight Time)
```

**Comment by LarsDenBakker** [comment]
Karma viewport doensn't work with karma-esm because we have to hack around karma to make it work with native es modules. There isn't anything we can do to change that.

We have been working on a new test runner, Web Test Runner, we will recommending this from open-wc soon. https://modern-web.dev/docs/test-runner/overview/

This properly supports testing different viewports: https://modern-web.dev/docs/test-runner/commands/#viewport

I will close this issue as we cannot change anything here.
