### ISSUE TITLE
[es-dev-server] errors on some browsers

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#1306]
Reported by @web-padawan 

```
Error: [BABEL] unknown: Preset /* your preset */ requires a filename to be set when babel is called directly,
  babel.transform(code, { filename: 'file.ts', presets: [/* your preset */] });
See https://babeljs.io/docs/en/options#filename for more information.
      at validateIfOptionNeedsFilename (/home/travis/build/vaadin/vaadin-app-layout/node_modules/@babel/core/lib/config/full.js:274:11)
      at /home/travis/build/vaadin/vaadin-app-layout/node_modules/@babel/core/lib/config/full.js:286:52
      at Array.forEach (<anonymous>)
      at validatePreset (/home/travis/build/vaadin/vaadin-app-layout/node_modules/@babel/core/lib/config/full.js:286:25)
      at loadPresetDescriptor (/home/travis/build/vaadin/vaadin-app-layout/node_modules/@babel/core/lib/config/full.js:293:3)
      at loadPresetDescriptor.next (<anonymous>)
      at recurseDescriptors (/home/travis/build/vaadin/vaadin-app-layout/node_modules/@babel/core/lib/config/full.js:107:30)
      at recurseDescriptors.next (<anonymous>)
      at loadFullConfig (/home/travis/build/vaadin/vaadin-app-layout/node_modules/@babel/core/lib/config/full.js:142:6)
      at loadFullConfig.next (<anonymous>)
      at Function.transform (/home/travis/build/vaadin/vaadin-app-layout/node_modules/@babel/core/lib/transform.js:25:45)
      at transform.next (<anonymous>)
      at evaluateSync (/home/travis/build/vaadin/vaadin-app-layout/node_modules/gensync/index.js:244:28)
      at Function.sync (/home/travis/build/vaadin/vaadin-app-layout/node_modules/gensync/index.js:84:14)
      at transform (/home/travis/build/vaadin/vaadin-app-layout/node_modules/@babel/core/lib/transform.js:36:54)
      at createPolyfillsLoader (/home/travis/build/vaadin/vaadin-app-layout/node_modules/polyfills-loader/src/create-polyfills-loader.js:249:20)
```

happens in Edge 18 in CI (also Mobile Safari 12.1)

**Comment by web-padawan** [comment]
Note: it started to also fail locally on Chrome after I have removed `node_modules`.

The dependency ranges that we have been using can be found here:
https://github.com/vaadin/vaadin-component-dev-dependencies/blob/v4.7.0/package.json

I pinned `es-dev-server` to 1.36.4 and `@open-wc/karma-esm` to 2.12.8 and then it worked.
