### ISSUE TITLE
[karma-esm] cannot execute snapshot testing in IE11 and Edge

### ISSUE THREAD

**Issue by goremikin** [open-wc/open-wc#1320]
Snapshot tests stopped working in IE11 and Edge (EdgeHTML) with the latest release.

The issue can be reproduced by running `npm init @open-wc`.

The test `shows initially the text "hey there Nr. 5!" and an "increment" button` fails with the following error:

```
TypeError: Unable to get property 'type' of undefined or null reference
   at assertHtmlEqualsSnapshot (base/node_modules/@open-wc/semantic-dom-diff/chai-dom-diff.js?transform-systemjs:114:11)
   at equalSnapshot (base/node_modules/@open-wc/semantic-dom-diff/chai-dom-diff.js?transform-systemjs:156:11)
   at methodWrapper (base/node_modules/chai/chai.js?transform-systemjs:7439:17)
   at _callee4$ (base/test/test-snapshots.test.js?transform-systemjs:201:19)
   at tryCatch (polyfills/regenerator-runtime.45f8b90cc0fac37d446d8da4b68e27f5.js:45:7)
   at invoke (polyfills/regenerator-runtime.45f8b90cc0fac37d446d8da4b68e27f5.js:271:9)
   at prototype[method] (polyfills/regenerator-runtime.45f8b90cc0fac37d446d8da4b68e27f5.js:97:9)
   at asyncGeneratorStep (base/test/test-snapshots.test.js?transform-systemjs:70:7)
   at _next (base/test/test-snapshots.test.js?transform-systemjs:92:11)
   at Anonymous function (polyfills/core-js.577a5602a7262d6256830802d4aaab43.js:8:30320)
```

**Comment by moodyjmz** [comment]
I see this too

**Comment by goremikin** [comment]
Seems to work with es-dev-server 1.39.1
