### ISSUE TITLE
[storybook:build] default project fails on windows

### ISSUE THREAD

**Issue by drBenway** [open-wc/open-wc#1356]
when I create a new project and I run "npm run storybook:build", I get the error below:
Is this a known issue?

```
C:\Projects\mynewtest-project>npm run storybook:build

> mynewtest-project@0.0.0 storybook:build C:\Projects\mynewtest-project
> build-storybook

[BABEL] Note: The code generator has deoptimised the styling of C:\Projects\mynewtest-project\node_modules\storybook-prebuilt\dist\storybook-prebuilt-351d7073.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of C:\Projects\mynewtest-project\node_modules\storybook-prebuilt\dist\storybook-prebuilt-351d7073.js as it exceeds the max of 500KB.

The service worker file was written to C:\Projects\mynewtest-project\storybook-static\sw.js
The service worker will precache 10 URLs, totaling 3.62 MB.

'C:Projectsmynewtest-project.storybookpreview.js' is imported by inline-entry.0.js, but could not be resolved – treating it as an external dependency
'C:Projectsmynewtest-project
ode_modulesstorybook-prebuiltweb-components.js' is imported by inline-entry.0.js, but could not be resolved – treating it as an external dependency
[BABEL] Note: The code generator has deoptimised the styling of C:\Projects\mynewtest-project\node_modules\storybook-prebuilt\dist\storybook-prebuilt-351d7073.js as it exceeds the max of 500KB.
> 1 | System.register(['C:Projectsmynewtest-project.storybookpreview.js', 'C:Projectsmynewtest-project
    |                                                                    ^ Unterminated string constant
  2 | ode_modulesstorybook-prebuiltweb-components.js'], function () {
  3 |   'use strict';
  4 |   var configure;
(node:16812) UnhandledPromiseRejectionWarning: SyntaxError: Unterminated string constant
    at ee (C:\Projects\mynewtest-project\node_modules\terser\dist\bundle.min.js:1:19391)
    at m (C:\Projects\mynewtest-project\node_modules\terser\dist\bundle.min.js:1:20704)
    at C:\Projects\mynewtest-project\node_modules\terser\dist\bundle.min.js:1:22849
    at C:\Projects\mynewtest-project\node_modules\terser\dist\bundle.min.js:1:25257
    at Object.L [as input] (C:\Projects\mynewtest-project\node_modules\terser\dist\bundle.min.js:1:25596)
    at a (C:\Projects\mynewtest-project\node_modules\terser\dist\bundle.min.js:1:27626)
    at s (C:\Projects\mynewtest-project\node_modules\terser\dist\bundle.min.js:1:27680)
    at p (C:\Projects\mynewtest-project\node_modules\terser\dist\bundle.min.js:1:28094)
    at _ (C:\Projects\mynewtest-project\node_modules\terser\dist\bundle.min.js:1:28210)
    at X (C:\Projects\mynewtest-project\node_modules\terser\dist\bundle.min.js:1:42572)
(node:16812) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16812) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
node is at version 12.15.0
npm at 6.13.4
windows version 10

## Steps to reproduces:
npm init @open-wc

app or web-component:Web component

(*)Demoing

scaffold Demoing

name of the web/component: mynewtest-project

structure to disk: Yes

Install with: npm

"`npm run start`" and "`npm run storybook`" work, "`npm run storybook:build`" throws the error above.

**Comment by LarsDenBakker** [comment]
Ive heard this complaint from other people as well. Will look into it.

**Comment by LarsDenBakker** [comment]
This was fixed with https://github.com/open-wc/open-wc/pull/1380 thanks for reporting it!
