### ISSUE TITLE
npm install gives errors

### ISSUE THREAD

**Issue by mercmobily** [open-wc/open-wc#1395]
After cloning open-wc, running `npm install` returns errors.
Here is what I am getting:

````
merc@merc-All-Series:~/Development/FORKS/open-wc3$ npm install --verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node', '/usr/bin/npm', 'install', '--verbose' ]
npm info using npm@6.13.4
npm info using node@v10.19.0
npm verb npm-session 1884acf221be5c96
npm info lifecycle @open-wc/root@~preinstall: @open-wc/root@
npm timing stage:loadCurrentTree Completed in 1971ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 26ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 654ms
npm http fetch GET 304 https://registry.npmjs.org/fsevents 194ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/nan 39ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/bindings 62ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/file-uri-to-path 77ms (from cache)
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 2376ms
npm timing stage:loadIdealTree Completed in 3734ms
npm timing stage:generateActionsToTake Completed in 108ms
npm verb correctMkdir /home/merc/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /home/merc/.npm/_locks/staging-5665b77b8bd6aa97.lock for /home/merc/Development/FORKS/open-wc3/node_modules/.staging
npm timing action:extract Completed in 261ms
npm timing action:finalize Completed in 102ms
npm timing action:refresh-package-json Completed in 109ms
npm timing action:preinstall Completed in 2ms
npm timing action:build Completed in 2ms
npm timing action:install Completed in 2ms
npm timing action:postinstall Completed in 1ms
npm verb unlock done using /home/merc/.npm/_locks/staging-5665b77b8bd6aa97.lock for /home/merc/Development/FORKS/open-wc3/node_modules/.staging
npm timing stage:executeActions Completed in 512ms
npm timing stage:rollbackFailedOptional Completed in 93ms
npm info linkStuff @open-wc/root@
npm info lifecycle @open-wc/root@~install: @open-wc/root@
npm info lifecycle @open-wc/root@~postinstall: @open-wc/root@

> @open-wc/root@ postinstall /home/merc/Development/FORKS/open-wc3
> npm run build

npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
npm info using npm@6.13.4
npm info using node@v10.19.0
npm verb run-script [ 'prebuild', 'build', 'postbuild' ]
npm info lifecycle @open-wc/root@~prebuild: @open-wc/root@
npm info lifecycle @open-wc/root@~build: @open-wc/root@

> @open-wc/root@ build /home/merc/Development/FORKS/open-wc3
> lerna run build

Configuring yargs through package.json is deprecated and will be removed in a future major release, please use the JS API instead.
Configuring yargs through package.json is deprecated and will be removed in a future major release, please use the JS API instead.
lerna notice cli v3.4.3
lerna info versioning independent
lerna info Executing command in 4 packages: "yarn run build"
lerna ERR! yarn run build exited 127 in '@import-maps/resolve'
lerna ERR! yarn run build stdout:
yarn run v1.22.0
$ babel src --out-dir dist --copy-files --include-dotfiles
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:
/bin/sh: 1: babel: not found
error Command failed with exit code 127.

lerna ERR! yarn run build exited 127 in '@import-maps/resolve'
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.
npm verb lifecycle @open-wc/root@~build: unsafe-perm in lifecycle true
npm verb lifecycle @open-wc/root@~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/merc/Development/FORKS/open-wc3/node_modules/.bin:/usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/merc/Development/FORKS/open-wc3/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
npm verb lifecycle @open-wc/root@~build: CWD: /home/merc/Development/FORKS/open-wc3
npm info lifecycle @open-wc/root@~build: Failed to exec build script
npm verb stack Error: @open-wc/root@ build: `lerna run build`
npm verb stack spawn ENOENT
npm verb stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
npm verb stack     at ChildProcess.emit (events.js:198:13)
npm verb stack     at maybeClose (internal/child_process.js:982:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
npm verb pkgid @open-wc/root@
npm verb cwd /home/merc/Development/FORKS/open-wc3
npm verb Linux 4.15.0-88-generic
npm verb argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm verb node v10.19.0
npm verb npm  v6.13.4
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! @open-wc/root@ build: `lerna run build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @open-wc/root@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 2157ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/merc/.npm/_logs/2020-03-02T05_27_33_320Z-debug.log
npm verb lifecycle @open-wc/root@~postinstall: unsafe-perm in lifecycle true
npm verb lifecycle @open-wc/root@~postinstall: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/merc/Development/FORKS/open-wc3/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
npm verb lifecycle @open-wc/root@~postinstall: CWD: /home/merc/Development/FORKS/open-wc3
npm http fetch POST 400 https://registry.npmjs.org/-/npm/v1/security/audits/quick 1828ms
npm info lifecycle @open-wc/root@~postinstall: Failed to exec postinstall script
npm verb stack Error: @open-wc/root@ postinstall: `npm run build`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:198:13)
npm verb stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:198:13)
npm verb stack     at maybeClose (internal/child_process.js:982:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
npm verb pkgid @open-wc/root@
npm verb cwd /home/merc/Development/FORKS/open-wc3
npm verb Linux 4.15.0-88-generic
npm verb argv "/usr/bin/node" "/usr/bin/npm" "install" "--verbose"
npm verb node v10.19.0
npm verb npm  v6.13.4
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @open-wc/root@ postinstall: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @open-wc/root@ postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 11418ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/merc/.npm/_logs/2020-03-02T05_27_35_283Z-debug.log
merc@merc-All-Series:~/Development/FORKS/open-wc3$ 
````

I tried a few things to hammer it in, and couldn't work out what was going on. It looks like `lerna` is not getting installed.

In case it helps:

````
 node --version
v10.19.0
merc@merc-All-Series:~/Development/FORKS/open-wc3$
````

**Comment by LarsDenBakker** [comment]
We use yarn workspaces, can you try with `yarn install`?

**Comment by mercmobily** [comment]
Done. I had  never used yarn before. I thought it was totally compatible with NPM -- well, I was obviously wrong.
Would you recommend yarn for my own projects?

**Comment by LarsDenBakker** [comment]
For regular projects there isn't much difference in everyday use, there are pros and cons for both. Yarn workspaces for monorepos is really good though, npm doesn't have that.

**Comment by mercmobily** [comment]
Thanks. I will look into it -- although I don't have monorepos to manage
(and hopefully never will!)
