### ISSUE TITLE
[semantic-dom-diff][chai-dom-diff] Shadow DOM Snapshot testing fails

### ISSUE THREAD

**Issue by 100stacks** [open-wc/open-wc#1540]
Hi there 👋! 

I’m running into an issue with Shadow DOM snapshot testing, so I created a repo using `open-wc init` to replicate the issue here: https://github.com/100stacks/shadow-dom-snapshot-equal-test

## `equalSnapshot()` fails to test Shadow DOM

Test `<hx-alert>` Shadow DOM against its snapshot.

```js
  it('shadow DOM should equal snapshot', async () => {
    const el = await fixture(html`
      <hx-alert title="foo"></hx-alert>
    `);

    // test fails
    expect(el).shadowDom.to.equalSnapshot();
  });
```

### Output
```
    ✖ shadow DOM should equal snapshot
HeadlessChrome 79.0.3945 (Mac OS X 10.13.6) HxAlert shadow DOM should equal snapshot FAILED
	TypeError: Cannot read property 'type' of null
	    at Proxy.call (node_modules/@open-wc/semantic-dom-diff/chai-dom-diff.js:91:26)
	    at Proxy.equalSnapshot (node_modules/@open-wc/semantic-dom-diff/chai-dom-diff.js:133:37)
	    at Proxy.equalSnapshot (node_modules/chai/chai.js:7824:25)
	    at Context.<anonymous> (test/hx-alert.test.js:46:29)
```
## Testing an arbitrary value does assert 

```js
  it('shadow DOM should FAIL arbitrary value check', async () => {
    const el = await fixture(html`
      <hx-alert title="foo"></hx-alert>
    `);

    expect(el).shadowDom.to.equal('bazz');
  });
```
### Output (compares the Shadow DOM)

```
FAILED TESTS:
  HxAlert
    ✖ shadow DOM should FAIL arbitrary value check
      HeadlessChrome 79.0.3945 (Mac OS X 10.13.6)
    AssertionError: expected '<h2>\n  foo Nr. 5!\n</h2>\n<button>\n  increment\n</button>\n' to equal 'bazz\n'

      + expected - actual

      -<h2>
      -  foo Nr. 5!
      -</h2>
      -<button>
      -  increment
      -</button>
      +bazz

    at assertHtmlEquals (node_modules/@open-wc/semantic-dom-diff/chai-dom-diff.js:49:17)
    at Proxy.handleDom (node_modules/@open-wc/semantic-dom-diff/chai-dom-diff.js:70:9)
    at Proxy.equal (node_modules/chai/chai.js:9039:33)
    at Context.<anonymous> (test/hx-alert.test.js:54:29)
```

## The error appears to occur here:

https://github.com/open-wc/open-wc/blob/5fe5f53896d3b574226c6388a9b31e969a80fcb5/packages/semantic-dom-diff/chai-dom-diff.js#L83-L120

Appreciate any assist...thanks guys!

**Comment by bennypowers** [comment]
We just released a new version, is this still relevant?

**Comment by 100stacks** [comment]
Hi @bennypowers, thank you for asking.  I updated my package.json to the latest version - `@open-wc/testing-v2.5.15`, and did a fresh `$yarn install`:

## Fresh install 
```bash
✔ ~/projects/sandbox/shadow-dom-snapshot-equal-test/hx-alert [open-wc-testing-v2.5.15 ↑·1|✔]
04:43 $ rm yarn.lock
✔ ~/projects/sandbox/shadow-dom-snapshot-equal-test/hx-alert [open-wc-testing-v2.5.15 ↑·1|✚ 1]
04:43 $ yarn install
yarn install v1.22.4
warning ../../../package.json: No license field
info No lockfile found.
[1/4] 🔍  Resolving packages...
info There appears to be trouble with your network connection. Retrying...
warning @open-wc/prettier-config@0.1.14: Please use Prettier 2 directly if you want to reproduce the exact same settings you can use { "printWidth": 100, "singleQuote": true, "arrowParens": "avoid", "trailingComma": "all" } in your prettier config.
warning lint-staged > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning lint-staged > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning @open-wc/testing-karma > mocha > mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning @open-wc/testing-karma > @open-wc/karma-esm > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "es-dev-server > @rollup/pluginutils@3.0.9" has unmet peer dependency "rollup@^1.20.0||^2.0.0".
warning "es-dev-server > @rollup/plugin-node-resolve@7.1.3" has unmet peer dependency "rollup@^1.20.0||^2.0.0".
warning "@open-wc/testing > sinon-chai@3.5.0" has unmet peer dependency "sinon@>=4.0.0 <10.0.0".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 64.22s.
```
I received unmet peer dependency warnings, though I didn't install them in the project `package.json`.  

<details>
  <summary>Project package.json</summary>

```json
{
  "name": "hx-alert",
  "version": "0.0.0",
  "description": "Webcomponent hx-alert following open-wc recommendations",
  "author": "hx-alert",
  "license": "MIT",
  "main": "index.js",
  "module": "index.js",
  "scripts": {
    "start": "es-dev-server --app-index demo/index.html --node-resolve --open --watch",
    "lint:eslint": "eslint --ext .js,.html . --ignore-path .gitignore",
    "format:eslint": "eslint --ext .js,.html . --fix --ignore-path .gitignore",
    "lint:prettier": "prettier \"**/*.js\" --check --ignore-path .gitignore",
    "format:prettier": "prettier \"**/*.js\" --write --ignore-path .gitignore",
    "lint": "npm run lint:eslint && npm run lint:prettier",
    "format": "npm run format:eslint && npm run format:prettier",
    "test": "karma start --coverage",
    "test:watch": "karma start --auto-watch=true --single-run=false"
  },
  "dependencies": {
    "lit-html": "^1.1.2",
    "lit-element": "^2.2.1"
  },
  "devDependencies": {
    "es-dev-server": "^1.23.0",
    "eslint": "^6.1.0",
    "@open-wc/eslint-config": "^2.0.0",
    "@open-wc/prettier-config": "^0.1.10",
    "husky": "^1.0.0",
    "lint-staged": "^8.0.0",
    "@open-wc/testing-karma": "^3.0.0",
    "deepmerge": "^3.2.0",
    "@open-wc/testing": "2.5.15"
  },
  "eslintConfig": {
    "extends": [
      "@open-wc/eslint-config",
      "eslint-config-prettier"
    ]
  },
  "prettier": "@open-wc/prettier-config",
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "*.js": [
      "eslint --fix",
      "prettier --write",
      "git add"
    ]
  }
}
```
</details>

## Re-ran the tests
```
04:44 $ yarn test
yarn run v1.22.4
warning ../../../package.json: No license field
$ karma start --coverage

START:
28 04 2020 04:45:07.865:WARN [filelist]: Pattern "/projects/sandbox/shadow-dom-snapshot-equal-test/hx-alert/__snapshots__/**/*.md" does not match any file.
28 04 2020 04:45:07.890:INFO [karma-server]: Karma v4.4.1 server started at http://0.0.0.0:9876/
28 04 2020 04:45:07.890:INFO [launcher]: Launching browsers ChromeHeadlessNoSandbox with concurrency unlimited
28 04 2020 04:45:07.894:INFO [launcher]: Starting browser ChromeHeadless
28 04 2020 04:45:08.342:INFO [HeadlessChrome 79.0.3945 (Mac OS X 10.13.6)]: Connected on socket Tlaht7-aKbzdbXBiAAAA with id 45830067
  HxAlert
    ✔ has a default title "Hey there" and counter 5
    ✔ increases the counter on button click
    ✔ can override the title via attribute
    ✔ passes the a11y audit
    ✖ [TEST FAILS] shadow DOM should equal snapshot
HeadlessChrome 79.0.3945 (Mac OS X 10.13.6) HxAlert [TEST FAILS] shadow DOM should equal snapshot FAILED
	TypeError: Cannot read property 'type' of null
	    at Proxy.call (node_modules/@open-wc/semantic-dom-diff/chai-dom-diff.js:128:26)
	    at Proxy.equalSnapshot (node_modules/@open-wc/semantic-dom-diff/chai-dom-diff.js:173:37)
	    at Proxy.equalSnapshot (node_modules/chai/chai.js:7824:25)
	    at Context.<anonymous> (test/hx-alert.test.js:46:29)
    ✖ shadow DOM should FAIL arbitrary value check
HeadlessChrome 79.0.3945 (Mac OS X 10.13.6) HxAlert shadow DOM should FAIL arbitrary value check FAILED
	AssertionError: expected '<h2>\n  foo Nr. 5!\n</h2>\n<button>\n  increment\n</button>\n' to equal 'bazz\n'
	    at assertHtmlEquals (node_modules/@open-wc/semantic-dom-diff/chai-dom-diff.js:76:17)
	    at Proxy.handleDom (node_modules/@open-wc/semantic-dom-diff/chai-dom-diff.js:100:9)
	    at Proxy.equal (node_modules/chai/chai.js:9039:33)
	    at Context.<anonymous> (test/hx-alert.test.js:54:29)

Finished in 0.18 secs / 0.047 secs @ 04:45:10 GMT-0500 (Central Daylight Time)

SUMMARY:
✔ 4 tests completed
✖ 2 tests failed

FAILED TESTS:
  HxAlert
    ✖ [TEST FAILS] shadow DOM should equal snapshot
      HeadlessChrome 79.0.3945 (Mac OS X 10.13.6)
    TypeError: Cannot read property 'type' of null
        at Proxy.call (node_modules/@open-wc/semantic-dom-diff/chai-dom-diff.js:128:26)
        at Proxy.equalSnapshot (node_modules/@open-wc/semantic-dom-diff/chai-dom-diff.js:173:37)
        at Proxy.equalSnapshot (node_modules/chai/chai.js:7824:25)
        at Context.<anonymous> (test/hx-alert.test.js:46:29)

    ✖ shadow DOM should FAIL arbitrary value check
      HeadlessChrome 79.0.3945 (Mac OS X 10.13.6)
    AssertionError: expected '<h2>\n  foo Nr. 5!\n</h2>\n<button>\n  increment\n</button>\n' to equal 'bazz\n'

      + expected - actual

      -<h2>
      -  foo Nr. 5!
      -</h2>
      -<button>
      -  increment
      -</button>
      +bazz

    at assertHtmlEquals (node_modules/@open-wc/semantic-dom-diff/chai-dom-diff.js:76:17)
    at Proxy.handleDom (node_modules/@open-wc/semantic-dom-diff/chai-dom-diff.js:100:9)
    at Proxy.equal (node_modules/chai/chai.js:9039:33)
    at Context.<anonymous> (test/hx-alert.test.js:54:29)


TOTAL: 2 FAILED, 4 SUCCESS

=============================== Coverage summary ===============================
Statements   : 100% ( 8/8 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 5/5 )
Lines        : 100% ( 8/8 )
================================================================================
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I uploaded the branch here: https://github.com/100stacks/shadow-dom-snapshot-equal-test/tree/open-wc-testing-v2.5.15

#### It looks like I'm still getting the same error with a baseline snapshot test. 😞Any thoughts about something I could be missing?

**Comment by 100stacks** [comment]
## Temporary workaround asserting against Element Shadow Root

As a temporary workaround, I'm asserting against the element.shadowRoot.innerHTML.  It doesn't compare snapshots.

ref: https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot/innerHTML

### Assert Chai rendered `shadowDom` to `el.shadowRoot.innerHTML`

```js
  it('chai rendered shadow DOM should equal element shadow Root DOM', async () => {
    const el = await fixture(html`
      <hx-alert title="foo"></hx-alert>
      `);
    const sr = el.shadowRoot.innerHTML;

    expect(el).shadowDom.to.equal(sr);
  });
```

#### Output
```html
HxAlert
    ✔ has a default title "Hey there" and counter 5
    ✔ increases the counter on button click
    ✔ can override the title via attribute
    ✔ passes the a11y audit
    ✖ [TEST FAILS] shadow DOM should equal snapshot
HeadlessChrome 79.0.3945 (Mac OS X 10.13.6) HxAlert [TEST FAILS] shadow DOM should equal snapshot FAILED
	TypeError: Cannot read property 'type' of null
	    at Proxy.call (node_modules/@open-wc/semantic-dom-diff/chai-dom-diff.js:128:26)
	    at Proxy.equalSnapshot (node_modules/@open-wc/semantic-dom-diff/chai-dom-diff.js:173:37)
	    at Proxy.equalSnapshot (node_modules/chai/chai.js:7824:25)
	    at Context.<anonymous> (test/hx-alert.test.js:46:29)
    ✖ shadow DOM should FAIL arbitrary value check
HeadlessChrome 79.0.3945 (Mac OS X 10.13.6) HxAlert shadow DOM should FAIL arbitrary value check FAILED
	AssertionError: expected '<h2>\n  foo Nr. 5!\n</h2>\n<button>\n  increment\n</button>\n' to equal 'bazz\n'
	    at assertHtmlEquals (node_modules/@open-wc/semantic-dom-diff/chai-dom-diff.js:76:17)
	    at Proxy.handleDom (node_modules/@open-wc/semantic-dom-diff/chai-dom-diff.js:100:9)
	    at Proxy.equal (node_modules/chai/chai.js:9039:33)
	    at Context.<anonymous> (test/hx-alert.test.js:54:29)
    ✔ chai rendered shadow DOM should equal element shadow Root DOM

Finished in 0.188 secs / 0.053 secs @ 12:47:07 GMT-0500 (Central Daylight Time)
```

**Comment by nina-rafieifar** [comment]
This is still happening in v2.5.32. Any updates?

**Comment by backlineint** [comment]
Also ran into this and would love to see snapshot testing supported.
