### ISSUE TITLE
[es-dev-server] File extension plugin error

### ISSUE THREAD

**Issue by goremikin** [open-wc/open-wc#1636]
I am facing the issue with `es-dev-server@1.50.1`. When trying to run the server, which is created programmatically, I get the following error:

```
TypeError: Cannot read property 'some' of undefined
      at Object.resolveMimeType (/node_modules/es-dev-server/dist/plugins/fileExtensionsPlugin.js:13:32)
      at pluginMimeTypeMiddleware (/node_modules/es-dev-server/dist/middleware/plugin-mime-type.js:19:103)
      at async responseTransformMiddlewareConfig (/node_modules/es-dev-server/dist/middleware/response-transform.js:6:9)
      at async pluginTransformMiddleware (/node_modules/es-dev-server/dist/middleware/plugin-transform.js:15:9)
      at async watchServedFilesMiddleware (/node_modules/es-dev-server/dist/middleware/watch-served-files.js:17:9)
      at async responseBodyCacheMiddleware (/node_modules/es-dev-server/dist/middleware/response-body-cache.js:70:9)
      at async etagCacheMiddleware (/node_modules/es-dev-server/dist/middleware/etag-cache.js:8:9)
      at async /node_modules/es-dev-server/dist/create-middlewares.js:86:9
      at async /node_modules/koa-compress/index.js:43:5
```
A quick investigation shows that `serverStart` function is never run from `fileExtensionsPlugin`, so `fileExtensions` variable is undefined.

**Comment by LarsDenBakker** [comment]
Ah, this hook is called only when you use `startServer` programmatically. I'll fix this.
