### ISSUE TITLE
Sample app with Rollup and TypeScript fails to build

### ISSUE THREAD

**Issue by abraham** [open-wc/open-wc#1654]
When generating a new app that only uses Rollup with TypeScript (no linting, testing, or demoing) doing a build fails with the following error:

> Error: Could not resolve entry module (out-tsc/src/cool-app.js).

The issue appears to be that without additional folders with TypeScript files the contents of `src` are placed in the root of `out-tsc` instead of landing in `out-tsc/src`.

By adding an empty file to `test/cool-app.test.ts` builds will complete without error.

Version info:
```console
$ node -v
v10.18.1
$ npm -v
6.14.4
```

Reproduction:

```console
$ npm init @open-wc

? What would you like to do today? › - Use arrow-keys. Return to submit.
❯   Scaffold a new project
    Upgrade an existing project

? What would you like to scaffold? › - Use arrow-keys. Return to submit.
    Web Component
❯   Application

? What would you like to add? ›  
Instructions:
    ↑/↓: Highlight option
    ←/→/[space]: Toggle selection
    a: Toggle all
    enter/return: Complete answer
◯   Linting (eslint & prettier)
◯   Testing (karma)
◯   Demoing (storybook)
◉   Building (rollup)

? Would you like to use typescript? › - Use arrow-keys. Return to submit.
    No
❯   Yes

? Would you like to scaffold examples files for? ›  
Instructions:
    ↑/↓: Highlight option
    ←/→/[space]: Toggle selection
    a: Toggle all
    enter/return: Complete answer
◉   Building (rollup)

? What is the tag name of your application/web component? › cool-app

./
├── cool-app/
│   ├── src/
│   │   ├── cool-app.ts
│   │   ├── CoolApp.ts
│   │   └── open-wc-logo.ts
│   ├── .editorconfig
│   ├── .gitignore
│   ├── custom-elements.json
│   ├── index.html
│   ├── LICENSE
│   ├── package.json
│   ├── README.md
│   ├── rollup.config.js
│   └── tsconfig.json

? Do you want to write this file structure to disk? › - Use arrow-keys. Return to submit.
❯   Yes
Writing..... done

? Do you want to install dependencies? › - Use arrow-keys. Return to submit.
    No
    Yes, with yarn
❯   Yes, with npm
Installing dependencies...
This might take some time...
Using npm to install...
You are all set up now!

All you need to do is run:
  cd cool-app
  npm run start

$ cd cool-app
$ npm run build
> cool-app@0.0.0 build /Users/abraham/Sandbox/cool-app
> rimraf dist && tsc && rollup -c rollup.config.js


./index.html → dist...
[!] Error: Could not resolve entry module (out-tsc/src/cool-app.js).
Error: Could not resolve entry module (out-tsc/src/cool-app.js).
    at error (/Users/abraham/Sandbox/cool-app/node_modules/rollup/dist/shared/rollup.js:161:30)
    at ModuleLoader.loadEntryModule (/Users/abraham/Sandbox/cool-app/node_modules/rollup/dist/shared/rollup.js:17547:16)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cool-app@0.0.0 build: `rimraf dist && tsc && rollup -c rollup.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cool-app@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/abraham/.npm/_logs/2020-05-18T02_27_29_159Z-debug.log
```

**Comment by LarsDenBakker** [comment]
@thepassle is this the same issue that was reported on slack before?

**Comment by thepassle** [comment]
😮 Could be!

Asked @petecarapetyan on slack to confirm its the same issue he ran into

**Comment by thepassle** [comment]
Just ran a clean install with only `building` as option, and I can reproduce.

So it looks like TSC doesnt maintain folder structure for some reason in the case if there's only a `src` directory 😕. Adding `"rootDir": "./"` to the `tsconfig.json` seems to fix it
