### ISSUE TITLE
[semantic-dom-diff] Snapshot failing when tag attribute contains stringify JSON (Object attribute in LitElement)

### ISSUE THREAD

**Issue by MaximePlancke** [open-wc/open-wc#1755]
Hi all,

I am using open-wc with LitElement and I am testing my components with snapshots. 

Here is an example of my test
```html
  it('create a button with custom text', async () => {
    const el = await fixture(html`
      <didomi-button
        container-id="containerId"
        text="${JSON.stringify({ content: 'Regular text' })}"
      ></didomi-button>
    `);

    expect(el).shadowDom.to.equalSnapshot();
  });
```

This component contains an other component `<didomi-text/>` which also take an object (stringify JSON) as prop.

First I create my snapshot, everything goes fine and I have something like : 
```html
<button class="didomi-save-button">
  <slot name="content">
    <didomi-text
      container-id="containerId"
      options="{"content":"Regular text"}"
    >
    </didomi-text>
  </slot>
</button>
```

The issue appear when I run my test again at the moment the snapshot is compared on that line : https://github.com/open-wc/open-wc/blob/master/packages/semantic-dom-diff/get-diffable-html.js#L230

The string coming from the snapshot contains non-escaped double quotes and we pass in the innerHTML this : 
```html
<button class="didomi-save-button">
  <slot name="content">
    <didomi-text
      container-id="containerId"
      options="{"content":"Regular text"}"
    >
    </didomi-text>
  </slot>
</button>
```

instead of 

```html
<button class="didomi-save-button">
  <slot name="content">
    <didomi-text
      container-id="containerId"
      options="{&quot;content&quot;:&quot;Regular text&quot;}"
    >
    </didomi-text>
  </slot>
</button>
```

Some more information: 

Error Message: 
```
Error: Script error. (:0)        at getDiffableHTML (node_modules/@open-wc/semantic-dom-diff/get-diffable-html.js:231:5)        at Proxy.getDiffableHTML (node_modules/@open-wc/semantic-dom-diff/chai-dom-diff.js:142:51)        at Proxy.call (node_modules/@open-wc/semantic-dom-diff/chai-dom-diff.js:173:37)        at Proxy.methodWrapper (node_modules/chai/chai.js:7824:25)        at Context.equalSnapshot (test/components/presentationals/didomi-button/didomi-button.test.js:30:29)
```

wrong HTML generated by the innerHTML method from the snapshot because of double quotes
```html
<button class="didomi-save-button">
  <slot name="content">
    <didomi-text
      "test"}"=""
      container-id="containerId"
      options="{"
      test":=""
    >
    </didomi-text>
  </slot>
</button>
```

Would it be possible to convert back the snapshot to a readable format for the innerHTML method before comparing?

Thanks in advance!

**Comment by MaximePlancke** [comment]
I solved my issue by using 

```
.text=${{ content: 'Regular text' }}
```

instead of 

```
text="${JSON.stringify({ content: 'Regular text' })}"
```

and I am testing my `text` attribute  like so:

```
expect(el.text).to.eql({...})
```
