### ISSUE TITLE
MODULE NOT FOUND Error in es-dev-server

### ISSUE THREAD

**Issue by lakshaysharmaadp** [open-wc/open-wc#1825]
```es-dev-server --app-index index.html --node-resolve --open --watch

internal/modules/cjs/loader.js:621
  throw e;
  ^

Error: No valid exports main found for 'C:\dev\wcr-microservices-tfs\wcr-cli\test\newapp\node_modules\@rollup\pluginutils'
    at resolveExportsTarget (internal/modules/cjs/loader.js:618:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:650:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:948:27)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\dev\wcr-microservices-tfs\wcr-cli\test\newapp\node_modules\es-dev-server\node_modules\@rollup\plugin-node-resolve\dist\index.js:11:19)
    at Module._compile (internal/modules/cjs/loader.js:1128:30) {
  code: 'MODULE_NOT_FOUND'
```

I get the above output when running a project created from npm init @open-wc

**Comment by LarsDenBakker** [comment]
I just tried a freshly scaffolded app, and that works fine for me. Can you share some more information? What options did you choose? What version of node are you using?

**Comment by lakshaysharmaadp** [comment]
npm version: 6.13.1
node version: v13.3.0

I chose to create an application and chose all the options

**Comment by LarsDenBakker** [comment]
node v13 is end of life unfortunately, can you try with node v12 or v14?

**Comment by lakshaysharmaadp** [comment]
Sure thing. My bad on not keeping up with node releases.

**Comment by LarsDenBakker** [comment]
It's pretty confusing honestly, and node v13 has a bug with native es modules which rollup pluginutils is using so it's breaking for a lot of people...

**Comment by lakshaysharmaadp** [comment]
It works now! Thank you.
