### ISSUE TITLE
unknown value `@open-wc`

### ISSUE THREAD

**Issue by spockz** [open-wc/open-wc#1898]
Running `npm init @open-wc` for me yields:

```
$ npm init @open-wc
npx: installed 30 in 18.72s
/Users/alessandro/.npm/_npx/6559/lib/node_modules/@open-wc/create/node_modules/command-line-args/dist/index.js:1342
        const err = new Error(`Unknown value: ${arg}`);
                    ^

UNKNOWN_VALUE: Unknown value: @open-wc
    at commandLineArgs (/Users/alessandro/.npm/_npx/6559/lib/node_modules/@open-wc/create/node_modules/command-line-args/dist/index.js:1342:21)
    at Object.<anonymous> (/Users/alessandro/.npm/_npx/6559/lib/node_modules/@open-wc/create/dist/generators/app/index.js:70:19)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.<anonymous> (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/alessandro/.npm/_npx/6559/lib/node_modules/@open-wc/create/dist/create.js:12:14)
    at Module._compile (internal/modules/cjs/loader.js:955:30) {
  name: 'UNKNOWN_VALUE',
  value: '@open-wc'
}
```

Versions:
macOS: 10.13.6
shell: zsh
node: 14.14.0
npm: 6.13.4

**Comment by LarsDenBakker** [comment]
🤔 that's odd, for me the same gives:

```
ri04pi@APM3LC02ZQK32MD6T temp % npm init @open-wc
npx: installed 30 in 3.184s

        _.,,,,,,,,,._
     .d''           ``b.       Open Web Components Recommendations
   .p'      Open       `q.
 .d'    Web Components  `b.    Start or upgrade your web component project with
 .d'                     `b.   ease. All our recommendations at your fingertips.
 ::   .................   ::
 `p.                     .q'   See more details at https://open-wc.org/init/
  `p.    open-wc.org    .q'
   `b.     @openWc     .d'
     `q..            ..,'      Note: you can exit any time with Ctrl+C or Esc
        '',,,,,,,,,,''


? What would you like to do today? › - Use arrow-keys. Return to submit.
❯   Scaffold a new project
    Upgrade an existing project
```

**Comment by spockz** [comment]
Okay, so how to go about debugging this? Is it using older/different versions of some dependencies by any chance? This is on a completely fresh install with fresh node and npm installs.

**Comment by LarsDenBakker** [comment]
I'm using the same version of node, and NPM 6.14.8. You could try updating your version of NPM, but it would be strange if that is the cause.

The error is that the `@open-wc` argument is passed to the node process that is started from the `npm init` command which correctly complains that is cannot do anything with the `@open-wc` argument.

**Comment by spockz** [comment]
I just tried it from fedora and it worked flawlessly.

**Comment by mlemnian** [comment]
I know this issue is closed, but recently I had the same issue.
I realized that my node (and npm and npx) binaries were located inside of my GraalVM bin-folder.
I moved the links away from the GraalVM versions and installed node and npm fresh via https://nodejs.org/en/download/
Now it works.
