### ISSUE TITLE
[eslint-plugin-lit-a11y] role-supports-aria error

### ISSUE THREAD

**Issue by dlockhart** [open-wc/open-wc#1940]
When linting a component, I'm getting the following error:

> TypeError: Cannot destructure property 'props' of 'roles.get(...)' as it is undefined.
Occurred while linting /Users/dlockhart/source/brightspace-ui/core/components/calendar/calendar.js:496
    at Object.enterElement (/Users/dlockhart/source/brightspace-ui/core/node_modules/eslint-plugin-lit-a11y/lib/rules/role-supports-aria-attr.js:45:32)
    at visit (/Users/dlockhart/source/brightspace-ui/core/node_modules/eslint-plugin-lit-a11y/template-analyzer/template-analyzer.js:320:17)
    at /Users/dlockhart/source/brightspace-ui/core/node_modules/eslint-plugin-lit-a11y/template-analyzer/template-analyzer.js:327:13
    at Array.forEach (<anonymous>)
    at visit (/Users/dlockhart/source/brightspace-ui/core/node_modules/eslint-plugin-lit-a11y/template-analyzer/template-analyzer.js:326:20)
    at /Users/dlockhart/source/brightspace-ui/core/node_modules/eslint-plugin-lit-a11y/template-analyzer/template-analyzer.js:327:13
    at Array.forEach (<anonymous>)
    at visit (/Users/dlockhart/source/brightspace-ui/core/node_modules/eslint-plugin-lit-a11y/template-analyzer/template-analyzer.js:326:20)
    at TemplateAnalyzer.traverse (/Users/dlockhart/source/brightspace-ui/core/node_modules/eslint-plugin-lit-a11y/template-analyzer/template-analyzer.js:335:5)
    at TaggedTemplateExpression (/Users/dlockhart/source/brightspace-ui/core/node_modules/eslint-plugin-lit-a11y/lib/rules/role-supports-aria-attr.js:39:20)

The line it's pointing to is this one:
https://github.com/BrightspaceUI/core/blob/1fab3c130cd6849e95ae578a5f87526dd431eaa8/components/calendar/calendar.js#L496

There are a few `role` usages in that template, but if I remove the `role="${ifDefined(role)}"` one -- where the local variable `role` can be `'dialog'` or `undefined` -- it fixes things.

**Comment by thepassle** [comment]
I'll take a look, thanks for reporting!

**Comment by thepassle** [comment]
Looks like we forgot to guard against expressions used as roles, in the case of `role=${foo}` we can't know the value of `foo`, so we just consider it valid.

I've created a fix here https://github.com/open-wc/open-wc/compare/fix/guard-role?expand=1 🙂 

Thanks again for reporting! That was quick 😄

**Comment by thepassle** [comment]
fixed in `eslint-plugin-lit-a11y@1.0.1` 👍 Should be released shortly

**Comment by dlockhart** [comment]
Awesome, thanks for the quick turnaround!
