### ISSUE TITLE
test randomly fails

### ISSUE THREAD

**Issue by Vi-vi-Vi** [open-wc/open-wc#2009]
Hello,

I have this component that I would like to test with the test runner.

./package.json

``` json
{
  "scripts": {
    "test": "web-test-runner --playwright --browsers chromium firefox webkit --coverage",
    "test:watch": "web-test-runner --watch"
  },
  "devDependencies": {
    "@open-wc/testing": "^2.5.32",
    "@web/test-runner": "^0.10.0",
    "@web/test-runner-playwright": "^0.6.6"
  },
}
```

./my-component/my-component.js

``` js
(async() => {

  const res = await fetch('/my-component/my-component.html');
  const template = document.createElement('template');
  template.innerHTML = await res.text();

  class MyComponent extends HTMLElement {
    constructor() {
      super();

      this.attachShadow({ mode: 'open' });
      this.shadowRoot.appendChild(template.content.cloneNode(true));
    }
  }

  window.customElements.define('my-component', MyComponent);
  })();
```

./my-component/my-component.html

```html
<style>
    h2 {
        color: red;
    }
</style>
<h2>Hello world!</h2>
```

./my-component/test/my-component.test.js

```js
import { fixture, expect } from '@open-wc/testing';

import '../my-component.js';

/**
 * @typedef {import('../my-component.js').MyComponent} MyComponent
 */

describe('HTML test', () => {
  it('has by default an empty string as label', async () => {
    const element = /** @type {MyComponent} */ (await fixture('<my-component></my-component>'));
    expect(element).to.exist;
  });
  it('component contains h2 with text', async () => {
    const element = /** @type {MyComponent} */ (await fixture('<my-component></my-component>'));
    expect(element).shadowDom.to.equal(`<h2>Hello world!</h2>`);
  });
  it('component is displayed in red color', async () => {
    const element = /** @type {MyComponent} */ (await fixture('<my-component></my-component>'));
    const el = element.shadowRoot.querySelector('h2');
    expect(getComputedStyle(el)).to.have.property('color', 'rgb(255, 0, 0)');
  });
});
```

when I run `npm run test` I get the following error with chromium:

```
my-component/test/my-component.test.js:

 ❌ HTML test > component contains h2 with text (failed on Chromium)
      at: node_modules/@open-wc/semantic-dom-diff/src/utils.js:44:24
      TypeError: Cannot read property 'innerHTML' of null
        at getCleanedShadowDom (node_modules/@open-wc/semantic-dom-diff/src/utils.js:44:24)
        at getShadowDomHtml (node_modules/@open-wc/semantic-dom-diff/chai-dom-diff.js:58:34)
        at Proxy.handleDom (node_modules/@open-wc/semantic-dom-diff/chai-dom-diff.js:95:18)
        at Proxy.overwritingMethodWrapper (node_modules/chai/chai.js:9039:33)
        at n.<anonymous> (my-component/test/my-component.test.js:16:34)

Chromium: |██████████████████████████████| 1/1 test files | 2 passed, 1 failed
Firefox:  |██████████████████████████████| 1/1 test files | 3 passed, 0 failed
Webkit:   |██████████████████████████████| 1/1 test files | 3 passed, 0 failed

Code coverage: 100 %
View full coverage report at coverage/lcov-report/index.html

Finished running tests in 4s with 1 failed tests.
```

but when I run in watch mode with the command `npm run test:watch`, everything is fine:

```
Chrome: |██████████████████████████████| 1/1 test files | 3 passed, 0 failed

Finished running tests, watching for file changes...
```

I do not understand why it works in the "watch" case and not in the other one.

Could it be a problem within the fixture function?

Best Regards,

**Comment by LarsDenBakker** [comment]
There is a race condition in your code. Fetching the template happens async, so by the time the test runs fetching may or may not have happened already.
