### ISSUE TITLE
Testing Web Components Thrown Exceptions

### ISSUE THREAD

**Issue by hugolopes3d** [open-wc/open-wc#2124]
Hello,

I have a web component built using vanilla and i am now performing some unit tests.

I have some validations on my arguments that triggers Error exceptions whenever the given attribute doesn't have the correct value.

The validation is triggered on the the method **connectedCallback**:

`public connectedCallback() {
        this.attachShadow({ mode: 'open' });
        this.validateArguments();
}`

Here is a example of the throwable Error:
`private validateMin(value: string) {
        if (!value) {
            throw new Error('The slider must have a min value defined!');
        }
        if (isNaN(+value)) {
            throw new Error('The slider min value should be a number!');
        }
        if (+value >= +this.max) {
            throw new Error('The min value for the slider is bigger than the max value!');
        }
    }`

How can i test this Error exceptions on the unit testing side? I tried several approaches without great success.

On the console i have the following output:

Browser logs:
      Error: The value for the slider should be between the min and max values!
        at HTMLElement.validateValue (src/components/slider/WebComp.ts:325:18)
        at HTMLElement.attributeChangedCallback (src/components/slider/WebComp.ts:170:17)
        at AttributeCommitter.commit (node_modules/lit-html/src/lib/parts.ts:116:19)
        at AttributePart.commit (node_modules/lit-html/src/lib/parts.ts:153:19)
        at TemplateInstance.update (node_modules/lit-html/src/lib/template-instance.ts:49:13)
        at NodePart.__commitTemplateResult (node_modules/lit-html/src/lib/parts.ts:300:15)
        at NodePart.commit (node_modules/lit-html/src/lib/parts.ts:241:11)
        at render (node_modules/lit-html/src/lib/render.ts:51:11)
        at litFixtureSync (node_modules/@open-wc/testing-helpers/src/litFixture.js:41:3)
        at fixtureSync (node_modules/@open-wc/testing-helpers/src/fixture-no-side-effect.js:28:12)
      Error: The value for the slider should be between the min and max values!
        at HTMLElement.validateValue (src/components/slider/WebComp.ts:325:18)
        at HTMLElement.validateArguments (src/components/slider/WebComp.ts:280:13)
        at HTMLElement.connectedCallback (src/components/slider/WebComp.ts:142:13)
        at NodePart.__insert (node_modules/lit-html/src/lib/parts.ts:256:29)
        at NodePart.__commitNode (node_modules/lit-html/src/lib/parts.ts:264:9)
        at NodePart.__commitTemplateResult (node_modules/lit-html/src/lib/parts.ts:301:11)
        at NodePart.commit (node_modules/lit-html/src/lib/parts.ts:241:11)
        at render (node_modules/lit-html/src/lib/render.ts:51:11)
        at litFixtureSync (node_modules/@open-wc/testing-helpers/src/litFixture.js:41:3)
        at fixtureSync (node_modules/@open-wc/testing-helpers/src/fixture-no-side-effect.js:28:12)

 ❌ custom-web-component > Slider test arguments
      Error: Uncaught Error: The value for the slider should be between the min and max values! (http://localhost:8000/dist/components/slider/WebComp.js:290)
        at AttributeCommitter.commit (node_modules/lit-html/src/lib/parts.ts:116:19)
        at AttributePart.commit (node_modules/lit-html/src/lib/parts.ts:153:19)
        at TemplateInstance.update (node_modules/lit-html/src/lib/template-instance.ts:49:13)
        at NodePart.__commitTemplateResult (node_modules/lit-html/src/lib/parts.ts:300:15)
        at NodePart.commit (node_modules/lit-html/src/lib/parts.ts:241:11)
        at render (node_modules/lit-html/src/lib/render.ts:51:11)
        at litFixtureSync (node_modules/@open-wc/testing-helpers/src/litFixture.js:41:3)
        at fixtureSync (node_modules/@open-wc/testing-helpers/src/fixture-no-side-effect.js:28:12)
        at src/components/slider/WebComp.test.ts:16:25

Thanks in advanced.

**Comment by bennypowers** [comment]
It's considered an anti-pattern for a custom element to throw an error just because it was added to the page.

Have you ever seen a `<video>` or `<select>` element that threw a javascript error just because you created it or wrote a page with one?

It might be better to expose an `error` property/attribute and have the element render an error state instead of throwing an error.

**Comment by LarsDenBakker** [comment]
I agree with what benny says. It might be possible with appendChild, but I'm not certain:

```
const el = document.createElement('my-element');
try {
  document.body.appendChild(el);
} catch (error) {
  ///
}
```
