### ISSUE TITLE
 chai-dom-diff throwing error in semantic-dom-diff using equalSnapshot

### ISSUE THREAD

**Issue by jvanderen1** [open-wc/open-wc#2128]
## Expected behavior

I have this basic test component that should work:

```javascript
// Imports
// -------

// Libraries
import { html, fixture, expect } from '@open-wc/testing';
import { spreadProps } from '@open-wc/lit-helpers';
// Components
import '../../js/01-basic/01-basic-setup.js';

// Internal
// --------

const getComponent = async (props) => (
    await fixture(html`<basic-setup ...="${spreadProps(props)}"></basic-setup>`)
);

// Testing
// -------

describe('01-basic-setup', () => {
    let component;

    describe('Rendering', () => {
        it('renders default correctly', async () => {
            component = await getComponent();
            await expect(component).shadowDom.to.equalSnapshot();
            await expect(component).shadowDom.to.be.accessible();
        });
    });
});
```

## Actual Behavior

An error is thrown inside of `chai-dom-diff`:

```bash
TypeError: Cannot destructure property 'index' of 'context' as it is undefined.
        at Proxy.assertHtmlEqualsSnapshot (node_modules\@open-wc\semantic-dom-diff\chai-dom-diff.js:122:13)
        at Proxy.equalSnapshot (node_modules\@open-wc\semantic-dom-diff\chai-dom-diff.js:173:37)
        at Proxy.methodWrapper (node_modules\chai\chai.js:7884:25)
        at o.<anonymous> (test\01-basic\01-basic-setup.test.js:26:48)
```

## Additional context

I run `npm test`. Here is my `package.json`:

```json
{
  "name": "lit-element-testing",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "owc-dev-server -o",
    "test": "web-test-runner --coverage",
    "test:watch": "web-test-runner --watch"
  },
  "dependencies": {
    "@open-wc/lit-helpers": "^0.3.12",
    "@polymer/paper-card": "^3.0.1",
    "@vaadin/router": "^1.2.0",
    "@vaadin/vaadin-tabs": "^2.1.1",
    "@webcomponents/webcomponentsjs": "^2.2.7",
    "lit-element": "^2.1.0",
    "lit-html": "^1.0.0",
    "pwa-helpers": "^0.9.1"
  },
  "devDependencies": {
    "@open-wc/semantic-dom-diff": "^0.19.4",
    "@open-wc/testing": "^2.5.32",
    "@web/test-runner": "^0.12.20",
    "owc-dev-server": "^0.1.1"
  }
}
```

**Comment by jvanderen1** [comment]
I believe the issue is with `window.__mocha_context__` not being available. #1845 would have helped catch this.
