### ISSUE TITLE
eslint-plugin-lit-a11y throws error with newer versions of peer packages

### ISSUE THREAD

**Issue by acory** [open-wc/open-wc#2367]
## Expected behavior

Linting to work.

## Actual Behavior
```
/node_modules/eslint-plugin-lit-a11y/lib/rules/accessible-emoji.js:85
                  ) ?? node.loc;
                     ^

SyntaxError: Unexpected token '?'
    at new Script (vm.js:88:7)
    at NativeCompileCache._moduleCompile (/home/acory/WORK/etools-infra/pmp/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/home/acory/WORK/etools-infra/pmp/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (/home/acory/WORK/etools-infra/pmp/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at /home/acory/WORK/etools-infra/pmp/node_modules/requireindex/index.js:52:28
```

## Additional context

Package  versions:
```
 "@typescript-eslint/eslint-plugin": "^5.7.0",
 "@typescript-eslint/parser": "^5.7.0",
 "@typescript-eslint/typescript-estree": "^5.7.0",
 "eslint": "^7.32.0",
 "eslint-config-prettier": "^8.3.0",
 "eslint-plugin-lit": "^1.6.1",
 "eslint-plugin-lit-a11y": "^2.2.0",
 "eslint-plugin-prettier": "^4.0.0",
 "prettier": "~2.5.1",
 "typescript": "^4.5.4"
```

`Node version: 12.22.7`

**Comment by thepassle** [comment]
This seems more like an issue with your node version, than to do with packages. Are you using a node version that supports nullish coalescing?

**Comment by acory** [comment]
Node version: 12.22.7. 
Not sure if it supports nullish coalescing, probably not, because I just downgraded eslint-plugin-lit-a11y from 2.2.0, to 1.1.0, and it doesn't throw the error on the 1.1.0 version.

**Comment by thepassle** [comment]
Seems like we introduced nullish coalescing somewhere between version 1.1.0 and 2.2.0 then. Nullish coalescing requires node 14. Since node 16 is LTS, i'll close this issue.
