### ISSUE TITLE
Failing build for container

### ISSUE THREAD

**Issue by lunchboxav** [open-wc/open-wc#2369]
## Expected behavior

I'm expecting the build to work fine in container. 

## Actual Behavior

I use docker and when I run `npm run build` I got this error instead

```
rimraf dist && rollup -c rollup.config.js && npm run analyze -- --exclude dist

[!] Error: ENOENT: no such file or directory, lstat '/tmp/tmp.h8A7kJ5oTe'
Error: ENOENT: no such file or directory, lstat '/tmp/tmp.h8A7kJ5oTe'
    at Object.realpathSync (fs.js:1470:7)
    at Object.<anonymous> (/work/ui/app/node_modules/temp-dir/index.js:9:13)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Object.require.extensions.<computed> [as .js] (/work/ui/app/node_modules/rollup/dist/shared/loadConfigFile.js:563:13)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/work/ui/app/node_modules/tempy/index.js:5:17)
```
## Additional context

I'm unsure about the version number, but I used `npm init @open-wc` about 3 weeks ago and create an application and checks all the options (linting, testing, demoing, building)

**Comment by bennypowers** [comment]
Is this a filesystem permissions problem in your container?
Would it be easier to run rollup outside of docker and copy the files into the container's volume?

**Comment by lunchboxav** [comment]
Hi @bennypowers yeah apparently it was some permissions issue in the container. We ended up fixing it. Thanks!
