### ISSUE TITLE
TypeError: Attempted to assign to readonly property

### ISSUE THREAD

**Issue by andyjessop** [open-wc/open-wc#2756]
## Expected behavior

Test:

```
test('should be accessible', async () => {
  const el = await fixture(html`<button-1></button-1>`);
  await expect(el).to.be.accessible();
});
```

Component:
```
import { html, LitElement, TemplateResult } from 'lit';
import { customElement } from 'lit/decorators.js';

@customElement('button-1')
export class TestButton extends LitElement {
  render(): TemplateResult {
    return html`<button>test</button>`;
  }
}
```

I expect this should either pass or fail with a valid error. 

## Actual Behavior

I get this error:

```
27 |         this.DOCUMENT_POSITION_FOLLOWING = NodeDocumentPositionEnum.following;
28 |         this.DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC = NodeDocumentPositionEnum.implementationSpecific;
29 |         this.DOCUMENT_POSITION_PRECEDING = NodeDocumentPositionEnum.preceding;
30 |         this.ownerDocument = null;
31 |         this.parentNode = null;
32 |         this.isConnected = false;
             ^
TypeError: Attempted to assign to readonly property.
      at new Node (/Users/andy/dev/node_modules/happy-dom/lib/nodes/node/Node.js:32:9)
      at new CharacterData (/Users/andy/dev/node_modules/happy-dom/lib/nodes/character-data/CharacterData.js:20:9)
      at new Text (/Users/andy/dev//node_modules/happy-dom/lib/nodes/text/Text.js:10:9)
      at createTextNode (/Users/andy/dev//node_modules/happy-dom/lib/nodes/document/Document.js:733:16)
      at n (/Users/andy/dev/node_modules/axe-core/axe.min.js:12:47754)
      at /Users/andy/dev/node_modules/axe-core/axe.min.js:12:52348
      at /Users/andy/dev/node_modules/axe-core/axe.min.js:12:6155
      at i (/Users/andy/dev/node_modules/axe-core/axe.min.js:12:251644)
      at /Users/andy/dev/node_modules/axe-core/axe.min.js:12:468499
✗ should be accessible [33.63ms]
```

## Additional context

Bun 1.0.18
Happy DOM ^12.10.3

**Comment by thepassle** [comment]
This looks like either an issue with axe-core, bun, or happy dom. I dont think theres much we can do here.
I do recommend testing your code in real browsers instead of mocked browser environments
