### ISSUE TITLE
semantic-dom-diff@0.9.0 - rollup missing

### ISSUE THREAD

**Issue by jorgecasar** [open-wc/open-wc#328]
We have installed this packages:

- `@open-wc/demoing-storybook@^0.1.0`
- `@open-wc/testing@^0.10.1`
- `@open-wc/testing-karma@^0.4.0`
- `@open-wc/testing-karma-bs@^0.2.0`

Running `npm install` we get this error and we showed that `chat-dom-equals` require `semantic-dom-diff` and something should be wrong in `@open-wc/testing@^0.10.0` because with `0.9.0` works fine.

```
> @open-wc/semantic-dom-diff@0.9.0 postinstall ./node_modules/@open-wc/semantic-dom-diff
> rollup -c rollup.config.js

Error: ENOENT: no such file or directory, lstat './node_modules/@open-wc/semantic-dom-diff/rollup.config.js'
    at Object.realpathSync (fs.js:1477:7)
    at runRollup (./node_modules/rollup/bin/rollup:1812:29)
    at Object.<anonymous> (./node_modules/rollup/bin/rollup:1867:5)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
    at executeUserCode (internal/bootstrap/node.js:526:15)
```

**Comment by LarsDenBakker** [comment]
the postinstall is meant to run after installing dependencies inside the repository itself, not when it is installed inside another project... will fix that
