### ISSUE TITLE
`npx owc-dev-server` requires local installation

### ISSUE THREAD

**Issue by djlauk** [open-wc/open-wc#366]
# Summary
Running `npx owc-dev-server` *without prior local installation* (e.g. without `npm i -D owc-dev-server`) does start owc-dev-server, but it will break later with an error, unable to find babel-plugin-bare-import-rewrite:

```
Error { Error: Cannot find module 'babel-plugin-bare-import-rewrite' from '/private/tmp/test'
    at Function.module.exports [as sync] (/Users/lauk/.npm/_npx/20056/lib/node_modules/owc-dev-server/node_modules/resolve/lib/sync.js:58:15)
    at resolveStandardizedName (/Users/lauk/.npm/_npx/20056/lib/node_modules/owc-dev-server/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePlugin (/Users/lauk/.npm/_npx/20056/lib/node_modules/owc-dev-server/node_modules/@babel/core/lib/config/files/plugins.js:54:10)
    at loadPlugin (/Users/lauk/.npm/_npx/20056/lib/node_modules/owc-dev-server/node_modules/@babel/core/lib/config/files/plugins.js:62:20)
    at createDescriptor (/Users/lauk/.npm/_npx/20056/lib/node_modules/owc-dev-server/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at items.map (/Users/lauk/.npm/_npx/20056/lib/node_modules/owc-dev-server/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/lauk/.npm/_npx/20056/lib/node_modules/owc-dev-server/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPluginDescriptors (/Users/lauk/.npm/_npx/20056/lib/node_modules/owc-dev-server/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
    at alias (/Users/lauk/.npm/_npx/20056/lib/node_modules/owc-dev-server/node_modules/@babel/core/lib/config/config-descriptors.js:63:49) code: 'MODULE_NOT_FOUND' }
```

# Steps to reproduce
```bash
mkdir /tmp/test
cd /tmp/test
polymer init --name polymer-3-starter-kit
# ... output ...
# ... `polymer init` will automatically run `npm install` at the end
npx owc-dev-server --app-index index.html --open
```

# Known workaround
This issue is specific to running owc-dev-server *through `npx`*, but *without local installation*. One possible workaround is to install owc-dev-server locally, i.e. `npm i -D owc-dev-server` or `yarn add --dev owc-dev-server`. Then it can also be run through `npx` just fine.

**Comment by LarsDenBakker** [comment]
If you didn't install `owc-dev-server` globally, using `npx owc-dev-server` will not run anything. It sounds like you don't have installed locally, but a broken global installation?

**Comment by daKmoR** [comment]
> If you didn't install owc-dev-server globally, using npx owc-dev-server will not run anything

I think that is incorrect... npx will check locally then globally and if it's not available it will install it for temporary use... it's the same behavior we have for `npm init`

**Comment by djlauk** [comment]
As far as I know @daKmoR is correct.

To be precise: I *never* installed owc-dev-server globally, only ever locally.
Running `npx owc-dev-server` (without prior local installation) does download owc-dev-server and put it into `$HOME/.npm/_npx/$NPX_PID/lib/node_modules/owc-dev-server` and put a symbolic link in `$HOME/.npm/_npx/$NPX_PID/bin/owc-dev-server` pointing at `../lib/node_modules/owc-dev-server/owc-dev-server.js`.

The process is running, and it will serve static files just fine, but as soon as it needs to rewrite a bare module specifier, it will break. I just double checked.

**Comment by LarsDenBakker** [comment]
do you see those babel plugins in the local or the global `node_modules`?

**Comment by djlauk** [comment]
In case of **local installed owc-dev-server** the plugin is **next to** owc-dev-server, on the **same level**:
```sh
$ cd /path/to/app
$ find node_modules -type d -name owc-dev-server
node_modules/owc-dev-server
$ find node_modules -type d -name babel-plugin-bare-import-rewrite
node_modules/babel-plugin-bare-import-rewrite
```

In case of **running through npx without installation of owc-dev-server** the plugin is located **below** owc-dev-server, on **another level**:
```sh
$ mkdir /tmp/test
$ cd /tmp/test
$ find . -type d
.
# no subdirectories, so owc-dev-server is not installed locally here
# using npx we can still start it
$ npx owc-dev-server &
[1] 41656
npx: installed 123 in 5.318s
owc-dev-server started on http://localhost:8080
  Serving files from './'.
$ cd ~/.npm/_npx/41656/
$ find . -type d -name owc-dev-server
./lib/node_modules/owc-dev-server
$ find . -type d -name babel-plugin-bare-import-rewrite
./lib/node_modules/owc-dev-server/node_modules/babel-plugin-bare-import-rewrite
```
