### ISSUE TITLE
Generator: linting command is broken

### ISSUE THREAD

**Issue by jhuesos** [open-wc/open-wc#398]
According to https://open-wc.org/linting/, if you want to add linting to an existing project you can run the command:

```
npm init @open-wc linting
```

I just tried and it is not working, output:

```
migration-research git:(feat/config-lint) npm init @open-wc linting                                                                                                            
npx: installed 29 in 9.993s
/home/USER/.npm/_npx/22985/lib/node_modules/@open-wc/create/node_modules/command-line-args/dist/index.js:1345
        throw err
        ^

UNKNOWN_VALUE: Unknown value: linting
    at commandLineArgs (/home/USER/.npm/_npx/22985/lib/node_modules/@open-wc/create/node_modules/command-line-args/dist/index.js:1342:21)
    at Object.<anonymous> (/home/USER/.npm/_npx/22985/lib/node_modules/@open-wc/create/dist/generators/app/index.js:76:48)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/USER/.npm/_npx/22985/lib/node_modules/@open-wc/create/dist/create.js:12:14)
 migration-research git:(feat/config-lint) npm -v
6.9.0
 migration-research git:(feat/config-lint) node -v
v10.15.3
 migration-research git:(feat/config-lint) 
```

**Comment by daKmoR** [comment]
oh, it seems we missed updating this documentation?

correct would be
```bash
npm init @open-wc
# Upgrade > Linting
```

care to create Pull Request to update it? pretty please :hugs:
