### ISSUE TITLE
Unable to run project, after installing npm init @open-wc

### ISSUE THREAD

**Issue by mullamohiddin** [open-wc/open-wc#433]
After installing npm init @open-wc , i am not able to run the application and throwing below error.
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 127.0.0.1:8080
    at Server.setupListenHandle [as _listen2] (net.js:1269:19)
    at listenInCluster (net.js:1334:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1460:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:62:10)
Emitted 'error' event at:
    at emitErrorNT (net.js:1313:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-tag@0.0.0 start: `owc-dev-server --open demo`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-tag@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by mullamohiddin** [comment]
Problem with port number. Already running one program on 8080 
After running npm start -- --port 8000 able to run.
