### ISSUE TITLE
Testing-karma 2 not working with webpack preprocessor

### ISSUE THREAD

**Issue by f-santos** [open-wc/open-wc#483]
My Karma configuration has webpack as a preprocessor. 
Once I update @open-wc/testing-karma from 1.1.2 to 2.0.0 (and change the necessary Breaking Changes specified in the [CHANGELOG.md](https://github.com/open-wc/open-wc/blob/master/packages/testing-karma/CHANGELOG.md)) when trying to run it through `npm run test` I receive the following result: 

```sh
> myproject@1.0.0 test C:\Users\myuser\myproject
> karma start

07 06 2019 11:17:11.933:ERROR [preprocess]: Can not load "webpack"!
  TypeError: Cannot read property 'transformPath' of undefined
    at preprocessorFactory (C:\Users\myuser\myproject\node_modules\karma-webpack\lib\karma-webpack.js:106:20)
    at Array.invoke (C:\Users\myuser\myproject\node_modules\di\lib\injector.js:75:15)
    at Injector.get (C:\Users\myuser\myproject\node_modules\di\lib\injector.js:48:43)
    at instantiatePreprocessor (C:\Users\myuser\myproject\node_modules\karma\lib\preprocessor.js:50:20)
    at Array.forEach (<anonymous>)
    at createPreprocessor (C:\Users\myuser\myproject\node_modules\karma\lib\preprocessor.js:68:20)
    at Array.invoke (C:\Users\myuser\myproject\node_modules\di\lib\injector.js:75:15)
    at get (C:\Users\myuser\myproject\node_modules\di\lib\injector.js:48:43)
    at C:\Users\myuser\myproject\node_modules\di\lib\injector.js:71:14
    at Array.map (<anonymous>)
    at Injector.invoke (C:\Users\myuser\myproject\node_modules\di\lib\injector.js:70:31)
    at Server.start (C:\Users\myuser\myproject\node_modules\karma\lib\server.js:127:22)

START:
07 06 2019 11:17:12.097:WARN [filelist]: Pattern "C:/Users/myuser/projects/myproject/__snapshots__/**/*.md" does not match any file.
07 06 2019 11:17:12.745:INFO [karma-server]: Karma v4.1.0 server started at http://0.0.0.0:9876/
07 06 2019 11:17:12.746:INFO [launcher]: Launching browsers Chrome_without_security with concurrency unlimited
07 06 2019 11:17:12.748:ERROR [karma-server]: Error: Found 1 load error
    at Server.webServer.listen (C:\Users\myuser\myproject\node_modules\karma\lib\server.js:182:27)
    at Object.onceWrapper (events.js:286:20)
    at Server.emit (events.js:203:15)
    at emitListeningNT (net.js:1313:10)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myproject@1.0.0 test: `karma start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the myproject@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\myuser\AppData\Roaming\npm-cache\_logs\2019-06-07T15_17_12_805Z-debug.log
```

Here is my karma.conf.js file content: 

```js
const createDefaultConfig = require('@open-wc/testing-karma/default-config');
const merge = require('webpack-merge');

let allTestFiles = [];
allTestFiles.push('karma.init.js');
allTestFiles.push('test/**/*.test.js');

module.exports = config => {
	config.set(
		merge.strategy({
			browsers: 'replace',
			customLaunchers: 'replace',
		})(createDefaultConfig(config), {
			files: config.grep ? [config.grep] : allTestFiles,
			browsers: ['Chrome_without_security'],
			customLaunchers: {
				Chrome_without_security: {
					base: 'Chrome',
					flags: ['--disable-web-security'],
				},
			},
			coverageIstanbulReporter: {
				thresholds: {
					global: {
						statements: 0,
						lines: 0,
						branches: 0,
						functions: 0,
					},
				},
			},
			preprocessors: {
				'karma.init.js': ['webpack'],
			},
		}),
	);
	return config;
};

```

**Comment by LarsDenBakker** [comment]
In `@open-wc/testing-karma` we no longer use webpack for regular tests but we use native es modules instead. This is probably why you are seeing this errors now. Can you try with a config without extensions?
