### ISSUE TITLE
webpack modern legacy config, non html entry results in error

### ISSUE THREAD

**Issue by askbeka** [open-wc/open-wc#529]
Passing 
```js
{
  input: path.resolve(__dirname, './src/index.js')
}
```
results in error

**Comment by LarsDenBakker** [comment]
The error is quite clear: 
```
Error: [WebpackIndexHTMLPlugin]: Entry must be a single index.html file
    at createError (/Users/larsdenbakker/Workspace/code/private/open-wc/packages/webpack-index-html-plugin/src/utils.js:13:10)
    at createEntrypoints (/Users/larsdenbakker/Workspace/code/private/open-wc/packages/webpack-index-html-plugin/src/create-entrypoints.js:32:13)
    at compiler.hooks.entryOption.tap (/Users/larsdenbakker/Workspace/code/private/open-wc/packages/webpack-index-html-plugin/webpack-index-html-plugin.js:94:24)
    at SyncBailHook.eval [as call] (eval at create (/Users/larsdenbakker/Workspace/code/private/open-wc/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:16)
    at SyncBailHook.lazyCompileHook (/Users/larsdenbakker/Workspace/code/private/open-wc/node_modules/tapable/lib/Hook.js:154:20)
    at WebpackOptionsApply.process (/Users/larsdenbakker/Workspace/code/private/open-wc/packages/building-webpack/node_modules/webpack/lib/WebpackOptionsApply.js:289:30)
    at webpack (/Users/larsdenbakker/Workspace/code/private/open-wc/packages/building-webpack/node_modules/webpack/lib/webpack.js:53:48)
    at options.map.options (/Users/larsdenbakker/Workspace/code/private/open-wc/packages/building-webpack/node_modules/webpack/lib/webpack.js:35:55)
    at Array.map (<anonymous>)
    at webpack (/Users/larsdenbakker/Workspace/code/private/open-wc/packages/building-webpack/node_modules/webpack/lib/webpack.js:35:40)
    at processOptions (/Users/larsdenbakker/Workspace/code/private/open-wc/packages/building-webpack/node_modules/webpack-cli/bin/cli.js:272:16)
    at yargs.parse (/Users/larsdenbakker/Workspace/code/private/open-wc/packages/building-webpack/node_modules/webpack-cli/bin/cli.js:388:3)
    at Object.parse (/Users/larsdenbakker/Workspace/code/private/open-wc/node_modules/yargs/yargs.js:567:18)
    at /Users/larsdenbakker/Workspace/code/private/open-wc/packages/building-webpack/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/Users/larsdenbakker/Workspace/code/private/open-wc/packages/building-webpack/node_modules/webpack-cli/bin/cli.js:390:3)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/larsdenbakker/Workspace/code/private/open-wc/packages/building-webpack/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

we are expecting an index.html file. 

`WebpackIndexHTMLPlugin` does support passing javascript as entrypoint but you will still need to provide a index.html template as it needs somewhere to write the output to. 

See: https://open-wc.org/building/webpack-index-html-plugin.html#non-index-html-entrypoints

I will update the error message and the webpack docs to mention this more clearly.

**Comment by LarsDenBakker** [comment]
Actually this is already documented on the `building-webpack` page: https://open-wc.org/building/building-webpack.html#common-extensions
