### ISSUE TITLE
esm: SyntaxError: missing after argument list

### ISSUE THREAD

**Issue by jimisdrpc** [open-wc/open-wc#595]
I am trying follow https://open-wc.org/testing/testing-karma.html#manual-setup and I got the error bellow. It seems it didn't reconize esm configuration. I have just copied karma.conf.js.

`xxx C:\_d\WSs\openwc-testing-vanilla-webcomponent
# npm i --save-dev @open-wc/testing-karma deepmerge karma
npm WARN deprecated @types/deepmerge@2.2.0: This is a stub types definition. deepmerge provides its own type definitions, so you do not need this installed.
npm WARN istanbul-instrumenter-loader@3.0.1 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN openwc-testing-vanilla-webcomponent No description
npm WARN openwc-testing-vanilla-webcomponent No repository field.
npm WARN openwc-testing-vanilla-webcomponent No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ deepmerge@4.0.0
+ karma@4.2.0
+ @open-wc/testing-karma@3.0.2
updated 3 packages and audited 3239 packages in 33.678s
found 0 vulnerabilities

resource@DESKTOP-AKCNE7F C:\_d\WSs\openwc-testing-vanilla-webcomponent
# npm run test

> @ test C:\_d\WSs\openwc-testing-vanilla-webcomponent
> karma start --coverage

17 07 2019 13:52:41.192:ERROR [config]: Invalid config file!
  C:\_d\WSs\openwc-testing-vanilla-webcomponent\karma.conf.js:18
    esm: {
    ^^^

SyntaxError: missing ) after argument list
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.parseConfig (C:\_d\WSs\openwc-testing-vanilla-webcomponent\node_modules\karma\lib\config.js:351:22)
    at new Server (C:\_d\WSs\openwc-testing-vanilla-webcomponent\node_modules\karma\lib\server.js:65:24)
    at Object.exports.run (C:\_d\WSs\openwc-testing-vanilla-webcomponent\node_modules\karma\lib\cli.js:291:7)
    at Object.<anonymous> (C:\_d\WSs\openwc-testing-vanilla-webcomponent\node_modules\karma\bin\karma:3:23)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ test: `karma start --coverage`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\resource\AppData\Roaming\npm-cache\_logs\2019-07-17T16_52_41_255Z-debug.log`

**Comment by LarsDenBakker** [comment]
Sorry, this is a typo in the docs. It should be:

```
const { createDefaultConfig } = require('@open-wc/testing-karma');
const merge = require('deepmerge');

module.exports = config => {
  config.set(
    merge(createDefaultConfig(config), {
      files: [
        // runs all files ending with .test in the test folder,
        // can be overwritten by passing a --grep flag. examples:
        //
        // npm run test -- --grep test/foo/bar.test.js
        // npm run test -- --grep test/bar/*
        { pattern: config.grep ? config.grep : 'test/**/*.test.js', type: 'module' }
      ],

      // see the karma-esm docs for all options
      esm: {
        // if you are using 'bare module imports' you will need this option
        nodeResolve: true
      }
    })
  );
  return config;
};
```

can you try with that?

**Comment by jimisdrpc** [comment]
Thanks for promptly replied. After that, it missed mocha. After I installed mocha I get an error that "could not resolve ... @open-wc/testing". I give a try by pointing to node-modules folder without success. Basically, I followed the steps to install manually and, in order to test, I copied the webcomponent and its test from open-wc scaffold generarted files.

# npm test                                                                                                                                                               
                                                                                                                                                                         
> @ test C:\_d\WSs\openwc-testing-vanilla-webcomponent                                                                                                                   
> karma start --coverage                                                                                                                                                 
                                                                                                                                                                         
                                                                                                                                                                         
START:                                                                                                                                                                   
17 07 2019 15:12:27.847:WARN [filelist]: Pattern "C:/_d/WSs/openwc-testing-vanilla-webcomponent/__snapshots__/**/*.md" does not match any file.                          
17 07 2019 15:12:27.873:INFO [karma-server]: Karma v4.2.0 server started at http://0.0.0.0:9876/                                                                         
17 07 2019 15:12:27.875:INFO [launcher]: Launching browsers ChromeHeadlessNoSandbox with concurrency unlimited                                                           
17 07 2019 15:12:27.881:INFO [launcher]: Starting browser ChromeHeadless                                                                                                 
17 07 2019 15:12:30.579:INFO [HeadlessChrome 75.0.3770 (Windows 10.0.0)]: Connected on socket MSn25ptaQPRdJgH5AAAA with id 51121781                                      
SyntaxError: C:\_d\WSs\openwc-testing-vanilla-webcomponent\test\openwc-learn.test.js: Could not resolve '../node_modules/@open-wc/testing'.                              
> 1 | import { html, fixture, expect } from "../node_modules/@open-wc/testing";                                                                                          
    | ^                                                                                                                                                                  
  2 |                                                                                                                                                                    
  3 | import "../src/openwc-learn.js";                                                                                                                                   
  4 |                                                                                                                                                                    
    at File.buildCodeFrameError (C:\_d\WSs\openwc-testing-vanilla-webcomponent\node_modules\@babel\core\lib\transformation\file\file.js:261:12)                          
    at NodePath.buildCodeFrameError (C:\_d\WSs\openwc-testing-vanilla-webcomponent\node_modules\@babel\traverse\lib\path\index.js:157:21)                                
    at tryResolve (C:\_d\WSs\openwc-testing-vanilla-webcomponent\node_modules\@open-wc\building-utils\forked-babel-plugin-bare-import-rewrite.js:122:23)                 
    at PluginPass.ImportDeclaration|ExportNamedDeclaration|ExportAllDeclaration (C:\_d\WSs\openwc-testing-vanilla-webcomponent\node_modules\@open-wc\building-utils\forke
d-babel-plugin-bare-import-rewrite.js:160:11)                                                                                                                            
    at newFn (C:\_d\WSs\openwc-testing-vanilla-webcomponent\node_modules\@babel\traverse\lib\visitors.js:193:21)                                                         
    at NodePath._call (C:\_d\WSs\openwc-testing-vanilla-webcomponent\node_modules\@babel\traverse\lib\path\context.js:53:20)                                             
    at NodePath.call (C:\_d\WSs\openwc-testing-vanilla-webcomponent\node_modules\@babel\traverse\lib\path\context.js:40:17)                                              
    at NodePath.visit (C:\_d\WSs\openwc-testing-vanilla-webcomponent\node_modules\@babel\traverse\lib\path\context.js:88:12)                                             
    at TraversalContext.visitQueue (C:\_d\WSs\openwc-testing-vanilla-webcomponent\node_modules\@babel\traverse\lib\context.js:118:16)                                    
    at TraversalContext.visitMultiple (C:\_d\WSs\openwc-testing-vanilla-webcomponent\node_modules\@babel\traverse\lib\context.js:85:17)                                  
    at TraversalContext.visit (C:\_d\WSs\openwc-testing-vanilla-webcomponent\node_modules\@babel\traverse\lib\context.js:144:19)                                         
    at Function.traverse.node (C:\_d\WSs\openwc-testing-vanilla-webcomponent\node_modules\@babel\traverse\lib\index.js:94:17)                                            
    at NodePath.visit (C:\_d\WSs\openwc-testing-vanilla-webcomponent\node_modules\@babel\traverse\lib\path\context.js:95:18)                                             
    at TraversalContext.visitQueue (C:\_d\WSs\openwc-testing-vanilla-webcomponent\node_modules\@babel\traverse\lib\context.js:118:16)                                    
    at TraversalContext.visitSingle (C:\_d\WSs\openwc-testing-vanilla-webcomponent\node_modules\@babel\traverse\lib\context.js:90:19)                                    
    at TraversalContext.visit (C:\_d\WSs\openwc-testing-vanilla-webcomponent\node_modules\@babel\traverse\lib\context.js:146:19)                                         
HeadlessChrome 75.0.3770 (Windows 10.0.0) ERROR: 'failed to load element http://localhost:9876/base/test/openwc-learn.test.js?025fae13f43b8940f56a0f7ae1b26e6e585ff5ea'  
HeadlessChrome 75.0.3770 (Windows 10.0.0) ERROR: 'failed to load element http://localhost:9876/base/test/openwc-learn.test.js?025fae13f43b8940f56a0f7ae1b26e6e585ff5ea'

**Comment by LarsDenBakker** [comment]
The `nodeResolve` option is sufficient for resolving the module paths

**Comment by jimisdrpc** [comment]
I don't think nodeResolve set to true in karma.conf is really helping to resolve the module paths. After I wrote the relative path I got it up and running. You can find the whole code in https://github.com/jimisdrpc/openwc-testing-vanilla-webcomponent. You can download the code and reproduce what I mean. Take the relative path out and you will not see nodeResolve resolving it

**Comment by daKmoR** [comment]
that repo seems to work fine for me?

what I did
```
git clone git@github.com:jimisdrpc/openwc-testing-vanilla-webcomponent.git
cd openwc-testing-vanilla-webcomponent
yarn
yarn test
```

still 2 successful test after changing in `test/openwc-learn.test.js`

```diff
-import { html, fixture, expect } from "../node_modules/@open-wc/testing";
+import { html, fixture, expect } from "@open-wc/testing";
```


what is your Operating System? Node/Npm Version?

**Comment by jimisdrpc** [comment]
You are right. I don't know why it is working now both approach. Thanks.

**Comment by daKmoR** [comment]
as long as it works 🤗
