### ISSUE TITLE
[testing-karma] missing mocha dependency

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#604]
On clean install, testing-karma throws ` Server start failed on port 9876: Error: Cannot find module 'mocha'` because it's not a dependency.

**Comment by jarrodek** [comment]
This and several more. The dependency is missing along with few other. 
I have installed all missing dependencies using `--no-save` option and I don't have this message anymore. However now I see the following error when trying to run tests:

```
$ npm test

> @open-wc/root@ test /Users/ppsztyc/workspace/open-wc
> karma start --coverage

START:
19 07 2019 11:13:16.991:INFO [karma-server]: Karma v4.2.0 server started at http://0.0.0.0:9876/
19 07 2019 11:13:16.994:INFO [launcher]: Launching browsers ChromeHeadlessNoSandbox with concurrency unlimited
19 07 2019 11:13:16.999:INFO [launcher]: Starting browser ChromeHeadless
19 07 2019 11:13:17.864:INFO [HeadlessChrome 75.0.3770 (Mac OS X 10.13.6)]: Connected on socket QH9XEC4sfCESIcTuAAAA with id 40960559
SyntaxError: /Users/ppsztyc/workspace/open-wc/packages/semantic-dom-diff/test/chai-dom-equals-snapshots.test.js: Could not resolve '@bundled-es-modules/chai'.
> 1 | import { assert, expect } from '@bundled-es-modules/chai';
    | ^
  2 | import './bdd-setup.js';
  3 | 
  4 | customElements.define(
    at File.buildCodeFrameError (/Users/ppsztyc/workspace/open-wc/node_modules/@babel/core/lib/transformation/file/file.js:261:12)
    at NodePath.buildCodeFrameError (/Users/ppsztyc/workspace/open-wc/node_modules/@babel/traverse/lib/path/index.js:157:21)
    at tryResolve (/Users/ppsztyc/workspace/open-wc/node_modules/@open-wc/building-utils/forked-babel-plugin-bare-import-rewrite.js:122:23)
    at PluginPass.ImportDeclaration|ExportNamedDeclaration|ExportAllDeclaration (/Users/ppsztyc/workspace/open-wc/node_modules/@open-wc/building-utils/forked-babel-plugin-bare-import-rewrite.js:160:11)
    at newFn (/Users/ppsztyc/workspace/open-wc/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/Users/ppsztyc/workspace/open-wc/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/ppsztyc/workspace/open-wc/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/ppsztyc/workspace/open-wc/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/Users/ppsztyc/workspace/open-wc/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (/Users/ppsztyc/workspace/open-wc/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/Users/ppsztyc/workspace/open-wc/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/Users/ppsztyc/workspace/open-wc/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/Users/ppsztyc/workspace/open-wc/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/Users/ppsztyc/workspace/open-wc/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/Users/ppsztyc/workspace/open-wc/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/Users/ppsztyc/workspace/open-wc/node_modules/@babel/traverse/lib/context.js:146:19)
SyntaxError: /Users/ppsztyc/workspace/open-wc/packages/semantic-dom-diff/test/chai-dom-equals.test.js: Could not resolve '@bundled-es-modules/chai'.
```

(there are few errors like this).

I went through each project in the `packages` folder to install dependencies (you should really have a post install script in the root package that does that - just for developers' mental health ;) but I have the same result. I believe it's a webpack configuration or missing some dependency but I'm bit busy to dig into the code and debug.

It also won't work to run test in a single project in `packages` directory:

```sh
$ cd packages/testing-helpers/
[ppsztyc@mbp ~/workspace/open-wc/packages/testing-helpers (master *)]$ npm test

> @open-wc/testing-helpers@1.0.14 test /Users/ppsztyc/workspace/open-wc/packages/testing-helpers
> karma start --coverage


START:
19 07 2019 11:17:14.680:WARN [filelist]: Pattern "/Users/ppsztyc/workspace/open-wc/packages/testing-helpers/__snapshots__/**/*.md" does not match any file.
19 07 2019 11:17:14.683:WARN [filelist]: Pattern "/Users/ppsztyc/workspace/open-wc/packages/testing-helpers/node_modules/accessibility-developer-tools/dist/js/axs_testing.js" does not match any file.
19 07 2019 11:17:14.697:INFO [karma-server]: Karma v4.2.0 server started at http://0.0.0.0:9876/
19 07 2019 11:17:14.697:INFO [launcher]: Launching browsers ChromeHeadlessNoSandbox with concurrency unlimited
19 07 2019 11:17:14.702:INFO [launcher]: Starting browser ChromeHeadless
19 07 2019 11:17:15.192:INFO [HeadlessChrome 75.0.3770 (Mac OS X 10.13.6)]: Connected on socket XtErhmufC72JPSwOAAAA with id 67283969
HeadlessChrome 75.0.3770 (Mac OS X 10.13.6) ERROR
  Uncaught TypeError: Failed to resolve module specifier "@bundled-es-modules/chai". Relative references must start with either "/", "./", or "../".
  at http://localhost:9876/context.html:0:0
  
  TypeError: Failed to resolve module specifier "@bundled-es-modules/chai". Relative references must start with either "/", "./", or "../".
HeadlessChrome 75.0.3770 (Mac OS X 10.13.6) ERROR
  Uncaught TypeError: Failed to resolve module specifier "@bundled-es-modules/chai". Relative references must start with either "/", "./", or "../".
  at http://localhost:9876/context.html:0:0
  
  TypeError: Failed to resolve module specifier "@bundled-es-modules/chai". Relative references must start with either "/", "./", or "../".

Finished in 0.737 secs / 0 secs @ 11:17:15 GMT-0700 (Pacific Daylight Time)

SUMMARY:
✔ 0 tests completed

=============================== Coverage summary ===============================
Statements   : Unknown% ( 0/0 )
Branches     : Unknown% ( 0/0 )
Functions    : Unknown% ( 0/0 )
Lines        : Unknown% ( 0/0 )
================================================================================
npm ERR! Test failed.  See above for more details.
```

**Comment by LarsDenBakker** [comment]
My issue is related to installing `testing-karma` as a dependency. 

If you want to run our repository you need to use yarn, as we use yarn workspaces. That will solve your problem.

**Comment by jarrodek** [comment]
OK, that helped. Thanks
