### ISSUE TITLE
[es-dev-server] errors thrown running server or tests

### ISSUE THREAD

**Issue by jarrodek** [open-wc/open-wc#778]
After updating dependencies just now I started seeing errors like this:

```
es-dev-server started on http://localhost:8001
  Serving files from '/home/pawel/workspace/arc/api-schema-document'.
  Opening browser on '/demo/'
  Using history API fallback, redirecting non-file requests to '/demo/index.html'
{ Error: Parse error /home/pawel/workspace/arc/api-schema-document/node_modules/@polymer/polymer/lib/utils/boot.js:25:9
    at parse (/home/pawel/workspace/arc/api-schema-document/node_modules/es-module-lexer/dist/lexer.cjs:1:469)
    at resolveModuleImports (/home/pawel/workspace/arc/api-schema-document/node_modules/es-dev-server/dist/utils/resolve-module-imports.js:203:48)
    at compileMiddleware (/home/pawel/workspace/arc/api-schema-document/node_modules/es-dev-server/dist/middleware/compile-middleware.js:136:69)
    at process._tickCallback (internal/process/next_tick.js:68:7) idx: 1036 }

Could not resolve module imports in /node_modules/@polymer/polymer/lib/utils/boot.js: Unable to parse the module, this can be due to experimental syntax or a bug in the parser.
{ Error: Parse error /home/pawel/workspace/arc/api-schema-document/node_modules/@polymer/polymer/lib/utils/unresolved.js:21:9
    at parse (/home/pawel/workspace/arc/api-schema-document/node_modules/es-module-lexer/dist/lexer.cjs:1:469)
    at resolveModuleImports (/home/pawel/workspace/arc/api-schema-document/node_modules/es-dev-server/dist/utils/resolve-module-imports.js:203:48)
    at compileMiddleware (/home/pawel/workspace/arc/api-schema-document/node_modules/es-dev-server/dist/middleware/compile-middleware.js:136:69)
    at process._tickCallback (internal/process/next_tick.js:68:7) idx: 755 }

Could not resolve module imports in /node_modules/@polymer/polymer/lib/utils/unresolved.js: Unable to parse the module, this can be due to experimental syntax or a bug in the parser.
{ Error: Parse error /home/pawel/workspace/arc/api-schema-document/node_modules/@polymer/font-roboto/roboto.js:12:9
    at parse (/home/pawel/workspace/arc/api-schema-document/node_modules/es-module-lexer/dist/lexer.cjs:1:469)
    at resolveModuleImports (/home/pawel/workspace/arc/api-schema-document/node_modules/es-dev-server/dist/utils/resolve-module-imports.js:203:48)
    at compileMiddleware (/home/pawel/workspace/arc/api-schema-document/node_modules/es-dev-server/dist/middleware/compile-middleware.js:136:69)
    at process._tickCallback (internal/process/next_tick.js:68:7) idx: 520 }

Could not resolve module imports in /node_modules/@polymer/font-roboto/roboto.js: Unable to parse the module, this can be due to experimental syntax or a bug in the parser.
```

I've checked the `boot.js` file and there's nothing wrong with it. Only open-wc dependencies got upgraded when I ran `npm upgrade` so it shouldn't be problem with Polymer. My components uses few Polymer components, hence dependency.

**Comment by LarsDenBakker** [comment]
Really sorry about this, we updated the parser we're using to fix another issue but it seems to have created another. Filed an issue for this upstream: https://github.com/guybedford/es-module-lexer/pull/32

In the meantime I'll downgrade.

**Comment by jarrodek** [comment]
thanks! it works now :)
