### ISSUE TITLE
[testing] SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by memee** [open-wc/open-wc#896]
Running tests on newly initialized project returns errors:
```
node -v
v10.16.3

npm -v
6.9.0

npm init @open-wc
npx: installed 29 in 7.555s

✔ What would you like to do today? › Scaffold a new project
✔ What would you like to scaffold? › Web Component
✔ What would you like to add? › Testing
✔ Would you like to scaffold examples files for? › Testing
✔ What is the tag name of your application/web component? … ally-input
✔ Do you want to write this file structure to disk? › Yes
Writing..... done
✔ Do you want to install dependencies? › Yes, with npm

cd ally-input2/
npm test

> ally-input@0.0.0 test /home/macio/WebstormProjects/ally-input
> karma start --coverage

START:
22 10 2019 10:36:24.341:WARN [filelist]: Pattern "/home/macio/WebstormProjects/ally-input2/__snapshots__/**/*.md" does not match any file.
22 10 2019 10:36:24.353:INFO [karma-server]: Karma v4.4.1 server started at http://0.0.0.0:9876/
22 10 2019 10:36:24.353:INFO [launcher]: Launching browsers ChromeHeadlessNoSandbox with concurrency unlimited
22 10 2019 10:36:24.356:INFO [launcher]: Starting browser ChromeHeadless
22 10 2019 10:36:24.593:INFO [HeadlessChrome 77.0.3865 (Linux 0.0.0)]: Connected on socket tmVjLNy-swdtItIUAAAA with id 92741135
HeadlessChrome 77.0.3865 (Linux 0.0.0) ERROR
  Uncaught SyntaxError: Unexpected token '<'
  at node_modules/source-map-support/browser-source-map-support.js:1:1
  
  SyntaxError: Unexpected token '<'
HeadlessChrome 77.0.3865 (Linux 0.0.0) ERROR
  Uncaught SyntaxError: Unexpected token '<'
  at node_modules/source-map-support/browser-source-map-support.js:1:1
  
  SyntaxError: Unexpected token '<'
```

**Comment by memee** [comment]
Sorry for this issue. It came out that it's my local configuration problem.
Under http://0.0.0.0:9876/base/node_modules/source-map-support/browser-source-map-support.js?0a776857d457dcbb7a4bc82b263431477788990d
nginx server was serving content
