### ISSUE TITLE
Failing test of newly scaffolded application

### ISSUE THREAD

**Issue by kuka-radovan** [open-wc/open-wc#987]
When running tests on newly scaffolded application, those tests are failing. Tests for **PageMain** are testing **PageOne**.

This is result of test:

```sh
npm run test
​
> test-test@0.0.0 test /.../test-test
> karma start --coverage
​
​
START:
14 11 2019 09:09:38.068:WARN [filelist]: Pattern "/.../test-test/__snapshots__/**/*.md" does not match any file.
14 11 2019 09:09:38.087:INFO [karma-server]: Karma v4.4.1 server started at http://0.0.0.0:9876/
14 11 2019 09:09:38.087:INFO [launcher]: Launching browsers ChromeHeadlessNoSandbox with concurrency unlimited
14 11 2019 09:09:38.092:INFO [launcher]: Starting browser ChromeHeadless
14 11 2019 09:09:40.333:INFO [HeadlessChrome 78.0.3904 (Mac OS X 10.14.6)]: Connected on socket hMioGKyDhpqm_GeJAAAA with id 96249521
  PageMain
    ✖ has a default title "Hey there" and counter 5
HeadlessChrome 78.0.3904 (Mac OS X 10.14.6) PageMain has a default title "Hey there" and counter 5 FAILED
        AssertionError: expected 'Hello open-wc world!' to equal 'Hey there'
            at Context.<anonymous> (components/page-main/test/page-main.test.js:11:25)
    ✖ shows initially the text "hey there Nr. 5!" and an "increment" button
HeadlessChrome 78.0.3904 (Mac OS X 10.14.6) PageMain shows initially the text "hey there Nr. 5!" and an "increment" button FAILED
        AssertionError: expected '<h1>\n  Hello open-wc world!\n</h1>\n<p>\n  Edit\n  <code>\n    src/MyApp.js\n  </code>\n  and save to reload.\n</p>\n<a\n  class="app-link"\n  href="https://open-wc.org/developing/#examples"\n  rel="noopener noreferrer"\n  target="_blank"\n>\n  Code examples\n</a>\n' to equal '<h2>\n  Hey there Nr. 5!\n</h2>\n<button>\n  increment\n</button>\n'
            at assertHtmlEquals (node_modules/@open-wc/semantic-dom-diff/chai-dom-diff.js:49:17)
            at Proxy.handleDom (node_modules/@open-wc/semantic-dom-diff/chai-dom-diff.js:70:9)
            at Proxy.overwritingMethodWrapper (node_modules/chai/chai.js:9039:33)
            at Context.<anonymous> (components/page-main/test/page-main.test.js:20:29)
    ✖ increases the counter on button click
HeadlessChrome 78.0.3904 (Mac OS X 10.14.6) PageMain increases the counter on button click FAILED
        TypeError: Cannot read property 'click' of null
            at Context.<anonymous> (components/page-main/test/page-main.test.js:30:42)
    ✔ can override the title via attribute
  PageOne
    ✔ has a default title "Hey there" and counter 5
    ✔ shows initially the text "hey there Nr. 5!" and an "increment" button
    ✔ increases the counter on button click
    ✔ can override the title via attribute
  TestTest
    ✔ has page "main" by default
    ✔ renders page-one if page property is set to pageOne
    ✔ changes the page if a menu link gets clicked
​
Finished in 0.243 secs / 0.049 secs @ 09:09:41 GMT+0100 (Central European Standard Time)
​
SUMMARY:
✔ 8 tests completed
✖ 3 tests failed
​
FAILED TESTS:
  PageMain
    ✖ has a default title "Hey there" and counter 5
      HeadlessChrome 78.0.3904 (Mac OS X 10.14.6)
    AssertionError: expected 'Hello open-wc world!' to equal 'Hey there'
​
      + expected - actual
​
      -Hello open-wc world!
      +Hey there
      
    at Context.<anonymous> (components/page-main/test/page-main.test.js:11:25)
​
​
    ✖ shows initially the text "hey there Nr. 5!" and an "increment" button
      HeadlessChrome 78.0.3904 (Mac OS X 10.14.6)
    AssertionError: expected '<h1>\n  Hello open-wc world!\n</h1>\n<p>\n  Edit\n  <code>\n    src/MyApp.js\n  </code>\n  and save to reload.\n</p>\n<a\n  class="app-link"\n  href="https://open-wc.org/developing/#examples"\n  rel="noopener noreferrer"\n  target="_blank"\n>\n  Code examples\n</a>\n' to equal '<h2>\n  Hey there Nr. 5!\n</h2>\n<button>\n  increment\n</button>\n'
​
      + expected - actual
​
      -<h1>
      -  Hello open-wc world!
      -</h1>
      -<p>
      -  Edit
      -  <code>
      -    src/MyApp.js
      -  </code>
      -  and save to reload.
      -</p>
      -<a
      -  class="app-link"
      -  href="https://open-wc.org/developing/#examples"
      -  rel="noopener noreferrer"
      -  target="_blank"
      ->
      -  Code examples
      -</a>
      +<h2>
      +  Hey there Nr. 5!
      +</h2>
      +<button>
      +  increment
      +</button>
      
    at assertHtmlEquals (node_modules/@open-wc/semantic-dom-diff/chai-dom-diff.js:49:17)
    at Proxy.handleDom (node_modules/@open-wc/semantic-dom-diff/chai-dom-diff.js:70:9)
    at Proxy.overwritingMethodWrapper (node_modules/chai/chai.js:9039:33)
    at Context.<anonymous> (components/page-main/test/page-main.test.js:20:29)
​
​
    ✖ increases the counter on button click
      HeadlessChrome 78.0.3904 (Mac OS X 10.14.6)
    TypeError: Cannot read property 'click' of null
        at Context.<anonymous> (components/page-main/test/page-main.test.js:30:42)
​
TOTAL: 3 FAILED, 8 SUCCESS
​
=============================== Coverage summary ===============================
Statements   : 96.77% ( 30/31 )
Branches     : 75% ( 3/4 )
Functions    : 100% ( 16/16 )
Lines        : 96.77% ( 30/31 )
================================================================================
14 11 2019 09:09:41.530:ERROR [reporter.coverage-istanbul]: Coverage for branches (75%) does not meet global threshold (80%)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test-test@0.0.0 test: `karma start --coverage`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the test-test@0.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I could look at it and send PR.

**Comment by bennypowers** [comment]
I reproduced on my computer
